import re

with open("public/presentation_en.html", "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    # Intro / Manifesto
    r'The methane fermentation process does not only produce biogas\. It transforms burdensome agricultural waste into excellent, odorless organic fertilizer\.': 'The methane fermentation process does more than just produce biogas. It transforms burdensome agricultural waste into a premium, odorless organic fertilizer.',
    r'A biogas plant doesn\'t just produce green energy\. By utilizing slurry and manure, it prevents spontaneous methane emissions into the atmosphere, making the process extremely climate-friendly\.': 'A biogas plant does more than produce green energy. By utilizing slurry and manure, it prevents spontaneous atmospheric methane emissions, making the process highly climate-friendly.',
    r'The SCADA system is the operational backbone of the installation\. It aggregates data from hundreds of sensors and precisely manages mixers, pumps, and CHP systems, ensuring biological reactor stability and maximizing methane yield\.': 'The SCADA system is the operational backbone of the plant. It aggregates data from hundreds of sensors and precisely controls mixers, pumps, and CHP systems to ensure biological stability and maximize methane yield.',
    r'We do not rely on assumptions\. Before we design the reactors, samples of your biomass undergo rigorous Biochemical Methane Potential \(BMP\) testing\.': 'We don\'t rely on guesswork. Before designing the reactors, we subject samples of your biomass to rigorous Biochemical Methane Potential (BMP) testing.',
    r'Accurate determination of how much methane a ton of your feedstock will produce\.': 'Precise determination of the methane yield per ton of your feedstock.',
    r'Supervision of thermal insulation assembly and reinforced concrete pouring precision\. Complete environmental sterility\.': 'Precision supervision of thermal insulation and reinforced concrete pouring. Ensuring a completely sterile environment.',
    r'Methane fermentation experts\. Environmental parameterization to maximize yield from the entrusted biomass\.': 'Methane fermentation experts. We parameterize the environment to maximize the yield of the entrusted biomass.',
    r'Engineering staff authorized to design high gas risk installations\.': 'Engineering staff certified to design high-risk gas installations.',
    r'Handing over the keys is just the beginning\. Our operations center monitors biological and mechanical parameters 24/7, ensuring continuous generation\.': 'Handing over the keys is just the beginning. Our operations center monitors biological and mechanical parameters 24/7 to ensure continuous power generation.',
    r'We manage the full administrative process: from the Project Information Sheet \(KIP\), through the environmental report, to the final building permit and energy concession\.': 'We handle the entire administrative process: from the Project Information Sheet (KIP) and environmental reports, to the final building permit and energy concession.',
    r'We use proprietary algorithms to select mixer power and pump efficiency depending on substrate rheology, reducing energy consumption by 15%\.': 'We apply proprietary algorithms to optimize mixer power and pump efficiency based on substrate rheology, reducing energy consumption by 15%.',
    r'We design integrated phase separation and digestate storage systems, optimizing transport and field fertilization costs\.': 'We design integrated phase separation and digestate storage systems to optimize transport and field fertilization costs.',
    r'A set of technical procedures and standards defining each phase of the installation\'s lifecycle\.': 'A comprehensive set of technical procedures and standards defining every phase of the plant\'s lifecycle.',
    r'We verify technology, estimate CAPEX, design, build\. The first m³ of biogas — in 14 months\.': 'We verify the technology, estimate CAPEX, design, and build. Your first m³ of biogas—in 14 months.',
    r'Every reactor component operates in extreme conditions — from corrosive H₂S to gas overpressure\. Zero compromises\.': 'Every reactor component operates under extreme conditions—from corrosive H₂S to gas overpressure. Zero compromises.',
    r'Extracellular enzymes break down polysaccharides, proteins, and fats into simple water-soluble monomers\.': 'Extracellular enzymes break down polysaccharides, proteins, and fats into simple, water-soluble monomers.',
    r'Methanogenic archaea synthesize methane from acetate and hydrogen\. The heart of the biogas plant economy is this very phase\.': 'Methanogenic archaea synthesize methane from acetate and hydrogen. This phase is the economic engine of the biogas plant.',
    r'From silage to methane in 28 days\. Each fermentation phase has its own microflora, its own pH, its own pace\. The art of biological engineering lies in making these four worlds coexist in one chamber\.': 'From silage to methane in 28 days. Each fermentation phase has its own microflora, pH, and pace. The art of biological engineering lies in harmonizing these four worlds within a single chamber.',
    r'We believe that a <span class="italic">biogas plant</span> is not just a source of electricity\. It is a tool that solves three problems at once: waste, energy, fertilization\.': 'We believe a <span class="italic">biogas plant</span> is more than just a power source. It is a comprehensive tool that simultaneously solves three challenges: waste, energy, and fertilization.',
    r'Agriculture, which once fed the nation, is today accused of methane emissions, slurry stench, and soil depletion\. Unjustly\. It is enough to close the loop\.': 'Agriculture, which once fed the nation, is now blamed for methane emissions, slurry odors, and soil depletion. This is unjust. The solution is simply closing the loop.',
    r'<span class="font-serif italic text-\[\#C6A87C\]">Every</span> ton of manure is not a problem — it is 60 m³ of biogas, 0\.13 MWh of electricity, 22 kg of potassium and phosphorus returning to the soil instead of lakes\. You just need the tools\.': '<span class="font-serif italic text-[#C6A87C]">Every</span> ton of manure is not a liability—it\'s 60 m³ of biogas, 0.13 MWh of electricity, and 22 kg of potassium and phosphorus returned to the soil rather than our lakes. You just need the right tools.',
    r'Our role is to provide these tools with a quality where nothing breaks for 25 years\. Stainless steel 1\.4571\. Concrete W10 XA3\. Tier-1 engines\. ABB controllers\. Zero compromises on material specification\.': 'Our role is to deliver these tools with a build quality designed to run flawlessly for 25 years. Stainless steel 1.4571. Concrete W10 XA3. Tier-1 engines. ABB controllers. Zero compromises on material specifications.',
    r'Because agricultural energy deserves no less\.': 'Because agricultural energy deserves nothing less.',
    
    # Field to Electricity sequence
    r'Spring\. 12 thousand seeds per hectare\. Every stalk is a future 0\.4 m³ of biogas\.': 'Spring. 12,000 seeds per hectare. Every stalk represents a future 0.4 m³ of biogas.',
    r'In the first year of cooperation, we measure not only the acreage — we measure sun, rain, and soil pH\. Polish energy corn has some of the highest methane potentials in Europe: 210 m³ of biogas from a ton of fresh mass\.': 'In our first year of cooperation, we assess more than just the acreage—we measure sun, rain, and soil pH. Polish energy corn has one of the highest methane potentials in Europe: 210 m³ of biogas per ton of fresh mass.',
    r'Silence in which archaea work non-stop\.': 'A silent environment where archaea work relentlessly.',
    r'Silage enters the dispenser at 6:00 AM\. Mixers rotate slowly, 8 revolutions per minute\. Methanogenic bacteria cannot stand oxygen, noise, or sudden changes\. This is a factory where the loudest sound is the roar of the cooler fan\.': 'Silage enters the dispenser at 6:00 AM. Mixers rotate slowly at 8 revolutions per minute. Methanogenic bacteria cannot tolerate oxygen, noise, or sudden changes. This is a biological factory where the loudest sound is the hum of the cooling fan.',
    r'After 28 days, biogas flows through the intake of the Tier-1 engine\. 499 electrical kW\.': 'After 28 days, biogas flows into the intake of a Tier-1 engine. 499 kW of electrical power.',
    r'The Jenbacher J312 engine burns biogas with milliampere precision\. Energy goes to the national grid, sold in RES auctions at a price contracted for 15 years\. Every hour of operation is approx\. 130 EUR gross — regardless of weather, season, or geopolitics\.': 'The Jenbacher J312 engine burns biogas with milliampere precision. The energy is fed into the national grid and sold in RES auctions at a contracted price locked in for 15 years. Every hour of operation yields approx. 130 EUR gross—regardless of weather, season, or geopolitics.',
    r'Unlike wind and solar — biogas works at night\. It works in December\. It works when the energy exchange jumps to 400 EUR/MWh on a frosty evening\. There is no energy crisis here — because the source grows in the neighboring field\.': 'Unlike wind and solar, biogas works at night. It works in December. It works when energy exchange prices spike to 400 EUR/MWh on a freezing winter evening. There is no energy crisis here—because the fuel grows in the neighboring field.',
    r'Digestate returns to the field\. 30 tons daily of full-value NPK fertilizer — closing the loop\.': 'The digestate returns to the field. 30 tons of premium NPK fertilizer daily—closing the loop.',
    r'What came out of the soil as corn returns as fertilizer\. Without weed seeds, without pathogens, without stench\. The farmer stops buying urea and phosphates — because he produces them himself, in his own methane factory\.': 'What sprang from the soil as corn returns as fertilizer. Free from weed seeds, pathogens, and odors. The farmer stops buying urea and phosphates—because he produces them himself in his own methane factory.',
    r'Reactor operates in maintenance mode\. Mixers slow — 4 rpm\. Constant temperature 38\.4 °C\.': 'The reactor operates in maintenance mode. Mixers run slowly at 4 rpm. Constant temperature of 38.4 °C.',
    r'Maximum CH₄ production\. CHP Efficiency reaches 44\.2%\. Pumping to the grid at full power\.': 'Peak CH₄ production. CHP efficiency reaches 44.2%. Exporting to the grid at maximum capacity.',
    r'Highest energy prices between 6-9 PM\. SCADA algorithm maximizes output\.': 'Highest energy prices between 6:00 PM and 9:00 PM. The SCADA algorithm maximizes output.',
    
    # Archea
    r'An archaeon with an irregular polygonal shape\. Produces 70% of methane in the reactor, decomposing acetate into CH₄ and CO₂\. Optimum pH 6\.8–7\.4\.': 'An irregularly shaped polygonal archaeon. It produces 70% of the reactor\'s methane by decomposing acetate into CH₄ and CO₂. Optimal pH is 6.8–7.4.',
    r'A rod 2–8 µm long\. Uses hydrogen and CO₂ to produce methane\. Essential in the initial phase when free fatty acids dominate\.': 'A rod-shaped bacterium 2–8 µm in length. It uses hydrogen and CO₂ to produce methane. Essential during the initial phase when free fatty acids dominate.',
    r'An anaerobe that breaks down cellulose and hemicellulose\. The first rung of the food chain in the reactor\. Works efficiently in the mesophilic process \(38 °C\)\.': 'An anaerobe that breaks down cellulose and hemicellulose. It forms the first rung of the reactor\'s food chain and operates highly efficiently in mesophilic conditions (38 °C).',
    r'10⁹ cells work in one drop of substrate\. Bacteria and archaea are our true engineers — we select the most efficient strains, adapted to the local reactor diet\.': 'A billion cells operate in a single drop of substrate. Bacteria and archaea are our true engineers—we select the most efficient strains tailored specifically to the local reactor diet.',
    
    # Economics & Glossary
    r'Biogas is not the cheapest\. It is not the most space-saving\. It is the only one that combines stability with a negative carbon footprint\.': 'Biogas isn\'t the cheapest. It isn\'t the most space-efficient. But it is the only energy source that combines baseload stability with a negative carbon footprint.',
    r'A biogas plant not only does not emit — it utilizes methane that would escape from slurry into the atmosphere anyway\. Hence −25 g/kWh\.': 'A biogas plant doesn\'t just achieve zero emissions—it actively utilizes methane that would otherwise escape from slurry into the atmosphere. Hence, a footprint of −25 g/kWh.',
    r'Digestate revenue, slurry disposal costs, energy independence, impact on local agriculture\. This would change the equation\.': 'Revenue from digestate, eliminated slurry disposal costs, energy independence, and the positive impact on local agriculture. This fundamentally changes the equation.',
    r'European directive regulating equipment in potentially explosive atmospheres\. All reactor elements working with methane are classified as EX zone 1 lub 2\.': 'The European directive regulating equipment in potentially explosive atmospheres. All reactor components exposed to methane are strictly classified as EX zone 1 or 2.',
    r'European directive regulating equipment in potentially explosive atmospheres\. All reactor elements working with methane are classified as EX zone 1 or 2\.': 'The European directive regulating equipment in potentially explosive atmospheres. All reactor components exposed to methane are strictly classified as EX zone 1 or 2.',
    r'Combined production of electricity and heat\. Total efficiency up to 90% — contrary to 35% with power alone\.': 'Combined Heat and Power. Reaches total efficiency of up to 90%—compared to just 35% for standalone electricity generation.',
    r'Percentage of time the installation is ready to operate\. GP provides 98% — approx\. 8,600 hours per year\.': 'The percentage of time the plant is fully operational. GP guarantees 98% availability—approx. 8,600 hours per year.',
    r'Turnkey contract model\. The contractor is responsible for the design, procurement, and execution of the investment, delivering a ready installation with a yield goal\.': 'A turnkey contract model. The contractor is fully responsible for the design, procurement, and execution of the investment, delivering a fully operational plant meeting specified yield guarantees.',
    r'Toxic corrosive gas\. Exceeding limits \(e\.g\., above 200 ppm\) risks damaging the CHP engine\.': 'A toxic, highly corrosive gas. Exceeding limits (e.g., above 200 ppm) risks severe damage to the CHP engine.',
    r'The final phase of anaerobic fermentation\. Archaea transform acetate and hydrogen into methane and carbon dioxide\. The heart of the business is this very phase\.': 'The final phase of anaerobic fermentation. Archaea transform acetate and hydrogen into methane and carbon dioxide. This phase is the true economic heart of the business.',
    r'Support system including auctions and feed-in tariffs \(FIT\)\. Agricultural biogas has its own basket — no competition with wind and solar\.': 'The support system including energy auctions and feed-in tariffs (FIT). Agricultural biogas operates within its own dedicated basket—without competing against wind and solar.',
    r'Fermentation byproduct\. Odorless, rich in nitrogen, phosphorus, potassium\. Replaces synthetic fertilizers\. 30 tons daily from 0\.5 MW\.': 'A fermentation byproduct. Odorless and rich in nitrogen, phosphorus, and potassium. Fully replaces synthetic fertilizers. A 0.5 plant yields 30 tons daily.',
    r'Supervisory control and data acquisition system\. Thousands of variables per second\. An algorithm controlling every valve, every pump\.': 'The Supervisory Control and Data Acquisition system. It processes thousands of variables per second, with an algorithm precisely controlling every valve and pump.',
    r'Regulatory body supervising pressure vessels, pipelines, and supervised equipment\. Every biogas plant is subject to annual inspections\.': 'The regulatory body supervising pressure vessels, pipelines, and critical equipment. Every biogas plant is subject to strict annual inspections.',
    r'Every industry has its language\. Here are 14 terms that separate an engineer from a dilettante\. Reads like the Encyclopaedia Britannica\.': 'Every industry has its own language. Here are 14 terms that separate the engineer from the dilettante. It reads like the Encyclopaedia Britannica.',
    r'We design every project to eight external standards\. We do not list them for marketing — we list them because they define the scope of responsibility towards the investor and supervisory bodies\.': 'We design every project according to eight rigorous external standards. We don\'t list them for marketing purposes—we list them because they define our strict scope of responsibility to both the investor and supervisory bodies.',
    r'Every biogas plant is only as good as its weakest weld\. We check each one with a non-destructive test\.': 'A biogas plant is only as reliable as its weakest weld. We verify every single one with non-destructive testing.',
    r'Green Plant Tech is a new entity, but we do not learn from the investor\'s mistakes\. Our team brings over 50 years of accumulated experience from infrastructure projects in Europe\.': 'Green Plant Tech may be a new entity, but we don\'t learn at the investor\'s expense. Our team brings over 50 years of combined experience executing major infrastructure projects across Europe.',
    
    # More cleanups
    r'An engineer doesn\'t believe in "almost tight"\. An engineer measures\.': 'An engineer doesn\'t believe in "almost tight." An engineer measures.',
    r'A biogas plant is a stable energy asset operating 8,000 hours per year\.': 'A biogas plant is a stable baseload energy asset operating 8,000 hours a year.',
    r'Heat recovery from engine cooling and exhaust gases\. Zero heating costs\.': 'Heat recovery from engine cooling systems and exhaust gases. Zero heating costs.',
    r'Digestate as a free alternative to urea and phosphates\.': 'Digestate serves as a free alternative to urea and phosphates.',
    r'Free from weed seeds and pathogens\.': 'Completely free from weed seeds and pathogens.',
    r'No troublesome odors during spreading\.': 'Free from the troublesome odors typical of raw manure spreading.',
    r'Decisions and permits \(from A to Z\)': 'Decisions and permits (end-to-end)',
    r'Operations, service, and settlements': 'Operations, maintenance, and settlements',
    r'Partnership <span class="serif-italic text-gold-accent">Terms\.</span>': 'Partnership <span class="serif-italic text-gold-accent">Terms.</span>',
    r'Key assumptions in 60 seconds\. We finalize parameters after the farm and location audit\.': 'Key assumptions in 60 seconds. We finalize all parameters following the farm and site audit.',
    r'0 PLN CAPEX contribution \(financed by Green Plant\)': '0 PLN CAPEX contribution (fully financed by Green Plant)',
    r'contribution to SPV \(not a sale\)': 'contribution to SPV (equity, not a sale)',
    r'base model of farmer share': 'baseline model for farmer equity share',
    r'FIT/FIP \(according to current regulations\)': 'FIT/FIP tariffs (according to current legislation)',
    r'Higher Profit per Hectare': 'Higher Yield per Hectare',
    r'Less Social Tension': 'Reduced Social Tensions',
    r'0\.7 ha of land \(contribution to SPV\)': '0.7 ha of land (contribution to SPV)',
    r'Feedstock: slurry, manure, biomass': 'Feedstock: slurry, manure, biomass',
}

for k, v in replacements.items():
    content = re.sub(k, v, content, flags=re.IGNORECASE)

with open("public/presentation_en.html", "w", encoding="utf-8") as f:
    f.write(content)
