import re

with open("greenplant_en.jsx", "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    r'Budujemy aktywa energetyczne, które transformują odpady w przewidywalny kapitał i niezależność operacyjną\.': 'We build energy assets that transform waste into predictable capital and operational independence.',
    r'§ I — Filozofia inżynierska // GP / 26': '§ I — Engineering Philosophy // GP / 26',
    r'Badamy potencjał metanowy Twojej biomasy w laboratorium\. Na tej podstawie kalibrujemy pojemność reaktorów\.': 'We test the methane potential of your biomass in the lab. Based on this, we calibrate the reactor capacity.',
    r'Inżynieria Processu': 'Process Engineering',
    r'Projektujemy układ hydrauliczny, systemy mieszania oraz wymiany ciepła\. Optymalizujemy przepływ wsadu\.': 'We design the hydraulic layout, mixing, and heat exchange systems. We optimize feedstock flow.',
    r'Nadzorujemy wylewanie szczelnych komór żelbetowych i instalację agregatów CHP klasy Tier-1\.': 'We supervise the pouring of gas-tight reinforced concrete chambers and the installation of Tier-1 CHP units.',
    r'Gnojowica Bydlęca': 'Cattle Slurry',
    r'Obornik Świński': 'Pig Manure',
    r'Wysłodki Buraczane': 'Beet Pulp',
    r'Precyzyjna kalibracja reaktora pod kątem charakterystyki fizykochemicznej wsadu\.': 'Precise reactor calibration tailored to the physicochemical characteristics of the feedstock.',
    r'Biogazownia to stabilne aktywo energetyczne działające 8000h rocznie\.': 'A biogas plant is a stable energy asset operating 8,000 hours per year.',
    r'Odzysk ciepła z chłodzenia silników i spalin\. Zero kosztów ogrzewania\.': 'Heat recovery from engine cooling and exhaust gases. Zero heating costs.',
    r'Poferment jako darmowa alternatywa dla mocznika i fosforanów\.': 'Digestate as a free alternative to urea and phosphates.',
    r'• OBIEG ZAMKNIĘTY • ZERO ODPADÓW • ROLNICTWO CYRKULARNE': '• CLOSED LOOP • ZERO WASTE • CIRCULAR AGRICULTURE',
    r'Process fermentacji metanowej nie tylko produkuje biogaz\. Przekształca on uciążliwe odpady rolnicze w doskonały, bezwonny nawóz organiczny\.': 'The methane fermentation process does not only produce biogas. It transforms burdensome agricultural waste into excellent, odorless organic fertilizer.',
    r'Zastępuje drogie nawozy syntetyczne \(N-P-K\)\.': 'Replaces expensive synthetic fertilizers (N-P-K).',
    r'Poprawia strukturę gleby i retencję wody\.': 'Improves soil structure and water retention.',
    r'Pozbawiony nasion chwastów i patogenów\.': 'Free from weed seeds and pathogens.',
    r'Brak uciążliwych odorów podczas rozlewania\.': 'No troublesome odors during spreading.',
    r'Biogazownia nie tylko produkuje zieloną energy\. Utylizując gnojowicę i obornik, zapobiega samoistnej emisji metanu do atmosfery, czyniąc proces ekstremalnie przyjaznym dla klimatu\.': 'A biogas plant doesn\'t just produce green energy. By utilizing slurry and manure, it prevents spontaneous methane emissions into the atmosphere, making the process extremely climate-friendly.',
    r'gnojowica \+ kiszonka': 'slurry + silage',
    r'Wsad: 21 t / dobę': 'Feedstock: 21 t / day',
    r'Wsad: 18 t / dobę': 'Feedstock: 18 t / day',
    r'odpady miejskie': 'municipal waste',
    r'odpady poubojowe': 'slaughterhouse waste',
    r'System SCADA to kręgosłup operacyjny instalacji\. Agreguje dane z setek czujników i precyzyjnie zarządza pracą mieszadeł, pomp oraz systemów CHP, zapewniając stabilność biologiczną reaktora i maksymalizację uzysku metanu\.': 'The SCADA system is the operational backbone of the installation. It aggregates data from hundreds of sensors and precisely manages mixers, pumps, and CHP systems, ensuring biological reactor stability and maximizing methane yield.',
    r'Nie opieramy się na przypuszczeniach\. Zanim zaprojektujemy reaktory, próbki Twojej biomasy przechodzą rygorystyczne testy wydajności metanowej \(BMP\)\.': 'We do not rely on assumptions. Before we design the reactors, samples of your biomass undergo rigorous Biochemical Methane Potential (BMP) testing.',
    r'Dokładne określenie ile metanu wyprodukuje tona Twojego surowca\.': 'Accurate determination of how much methane a ton of your feedstock will produce.',
    r'Badanie suchej masy, zawartości popiołu oraz stosunku węgla do azotu \(C:N\)\.': 'Analysis of dry matter, ash content, and carbon-to-nitrogen (C:N) ratio.',
    r'Nadzór nad precyzją montażu izolacji termicznej i wylewek żelbetowych\. Pełna sterylność środowiska\.': 'Supervision of thermal insulation assembly and reinforced concrete pouring precision. Complete environmental sterility.',
    r'Eksperci od fermentacji metanowej\. Parametryzacja środowiska pod kątem maksymalizacji uzysku z powierzonej biomasy\.': 'Methane fermentation experts. Environmental parameterization to maximize yield from the entrusted biomass.',
    r'Kadra inżynierska z uprawnieniami do projektowania instalacji o wysokim ryzyku gazowym\.': 'Engineering staff authorized to design high gas risk installations.',
    r'Przekazanie kluczy to dopiero początek\. Nasze centrum operacyjne monitoruje parametry biologiczne i mechaniczne 24/7, zapewniając ciągłość generacji\.': 'Handing over the keys is just the beginning. Our operations center monitors biological and mechanical parameters 24/7, ensuring continuous generation.',
    r'Zabezpieczenie przeciwwybuchowe EX dla stref zagrożonych metanem\.': 'EX explosion protection for methane hazard zones.',
    r'Dozór techniczny nad zbiornikami ciśnieniowymi i rurociągami\.': 'Technical supervision over pressure vessels and pipelines.',
    r'Zintegrowane systemy oddymiania i aktywne pochodnie bezpieczeństwa\.': 'Integrated smoke exhaust systems and active safety flares.',
    r'Zgodność z europejskimi normami maszynowymi i bezpieczeństwa pracy\.': 'Compliance with European machinery and occupational safety standards.',
    r'Metodologia Pozyskiwania Decyzji': 'Permit Acquisition Methodology',
    r'Board of Directorszamy pełnym procesem administracyjnym: od Karty Informacyjnej Przedsięwzięcia \(KIP\), przez raport środowiskowy, aż po ostateczne PNB i koncesję energetyczną\.': 'We manage the full administrative process: from the Project Information Sheet (KIP), through the environmental report, to the final building permit and energy concession.',
    r'Parametryzacja Hydrauliki Processowej': 'Process Hydraulics Parameterization',
    r'Stosujemy autorskie algorytmy doboru mocy mieszadeł i wydajności pomp w zależności od reologii substratu, co redukuje zużycie energii o 15%\.': 'We use proprietary algorithms to select mixer power and pump efficiency depending on substrate rheology, reducing energy consumption by 15%.',
    r'Architektura Cyberbezpieczeństwa': 'Cybersecurity Architecture',
    r'Systemy SCADA pracują w odizolowanych sieciach VLAN z szyfrowanym dostępem VPN, zapewniając ochronę przed nieautoryzowanym dostępem do sterowników PLC\.': 'SCADA systems operate in isolated VLAN networks with encrypted VPN access, ensuring protection against unauthorized access to PLC controllers.',
    r'Logistyka Pofermentu i Odwadniania': 'Digestate and Dewatering Logistics',
    r'Projektujemy zintegrowane systemy separacji faz i magazynowania pofermentu, optymalizując koszty transportu i nawożenia na polach\.': 'We design integrated phase separation and digestate storage systems, optimizing transport and field fertilization costs.',
    r'Zbiór procedur i standardów technicznych definiujących każdą fazę życia instalacji\.': 'A set of technical procedures and standards defining each phase of the installation\'s lifecycle.',
    r'Nasze zespoły inżynierskie i serwisowe operują na terenie całego kraju, zapewniając wsparcie techniczne w każdym zakątku Polski\.': 'Our engineering and service teams operate nationwide, providing technical support in every corner of the country.',
    r'Weryfikujemy technologię, szacujemy CAPEX, projektujemy, budujemy\. Pierwszy m³ biogazu — w 14 miesięcy\.': 'We verify technology, estimate CAPEX, design, build. The first m³ of biogas — in 14 months.',
    r'Dział handlowy \+ inżynier': 'Sales department + engineer',
    r'rolniczych i komunalnych\.': 'agricultural and municipal.',
    r'zoptymalizowane pod kątem uzysku metanowego\.': 'optimized for methane yield.',
    r'Substrat — z polskich pól': 'Feedstock — from local fields',
    r'Wszelkie prawa zastrzeżone': 'All rights reserved',
    r'Stal nierdzewna 1\.4571\. Trzy łopaty hydrodynamiczne 18\.5 kW\.': 'Stainless steel 1.4571. Three hydrodynamic blades 18.5 kW.',
    r'Odporność termiczna -40 do \+80°C\.': 'Thermal resistance -40 to +80°C.',
    r'Beton klasy C35/45\. Szczelność gazowa P10\. Izolacja 20cm wełna mineralna\.': 'Concrete class C35/45. Gas tightness P10. Insulation 20cm mineral wool.',
    r'Dozownik z homogenizatorem\. 21 t/dobę\. Czujnik suchej masy\.': 'Dispenser with homogenizer. 21 t/day. Dry matter sensor.',
    r'Separator faz\. Suchy nawóz organiczny \+ ciecz pofermentacyjna\.': 'Phase separator. Dry organic fertilizer + liquid digestate.',
    r'pH, ORP, temperatura, lotne kwasy tłuszczowe \(VFA\)\. Próbkowanie ciągłe\.': 'pH, ORP, temperature, volatile fatty acids (VFA). Continuous sampling.',
    r'Spalanie biogazu w razie nadciśnienia\. Norma ATEX zone 1\.': 'Biogas flaring in case of overpressure. ATEX zone 1 standard.',
    r'Każdy komponent reaktora pracuje w warunkach skrajnych — od korozyjnego H₂S po nadciśnienie gazowe\. Zero compromises\.': 'Every reactor component operates in extreme conditions — from corrosive H₂S to gas overpressure. Zero compromises.',
    r'Hydroliza': 'Hydrolysis',
    r'Enzymy zewnątrzkomórkowe rozkładają wielocukry, białka i tłuszcze do prostych monomerów rozpuszczalnych w wodzie\.': 'Extracellular enzymes break down polysaccharides, proteins, and fats into simple water-soluble monomers.',
    r'Acydogeneza': 'Acidogenesis',
    r'Bakterie fermentacyjne przekształcają monomery w krótkołańcuchowe kwasy tłuszczowe, wodór i dwutlenek węgla\.': 'Fermentative bacteria convert monomers into short-chain fatty acids, hydrogen, and carbon dioxide.',
    r'Acetogeneza': 'Acetogenesis',
    r'Bakterie acetogenne utleniają wyższe kwasy tłuszczowe do octanu — substratu właściwego dla metanogenów\.': 'Acetogenic bacteria oxidize higher fatty acids to acetate — the proper substrate for methanogens.',
    r'Metanogeneza': 'Methanogenesis',
    r'Archeony metanogenne syntezują metan z octanu i wodoru\. Sercem ekonomii biogazowni jest właśnie ta faza\.': 'Methanogenic archaea synthesize methane from acetate and hydrogen. The heart of the biogas plant economy is this very phase.',
    r'jednej cząsteczki\.': 'one molecule.',
    r'Od kiszonki do metanu w 28 dni\. Każda faza fermentacji ma własną mikroflorę, własne pH, własne tempo\. Sztuka inżynierii biologicznej polega na tym, by te cztery światy współistniały w jednej komorze\.': 'From silage to methane in 28 days. Each fermentation phase has its own microflora, its own pH, its own pace. The art of biological engineering lies in making these four worlds coexist in one chamber.',
    r'Czas, w którym energia <br/>': 'The time when energy <br/>',
    r'dobiega końca\. Nadchodzi <br/>': 'comes to an end. The era <br/>',
    r'epoka, w której każde <br/>': 'is arriving where every <br/>',
    r'gospodarstwo staje się <br/>': 'farm becomes <br/>',
    r'Złożono krojem Cormorant Garamond': 'Typeset in Cormorant Garamond',
    r'Bydło, drób': 'Cattle, poultry',
    r'Buraki, bydło': 'Beets, cattle',
    r'Odpady komunalne': 'Municipal waste',
    r'Wywar gorzelniany': 'Distillery stillage',
    r'Ok\. 180 czynnych biogazowni rolniczych w Polsce\. Najgęściej w Wielkopolsce i Mazowszu — tam, gdzie koncentruje się hodowla i przemysł rolno-spożywczy\.': 'Approx. 180 active agricultural biogas plants in Poland. Most densely in Greater Poland and Mazovia — where livestock breeding and agri-food industry are concentrated.',
    r'Wierzymy, że <span className="italic">biogazownia</span> nie jest tylko źródłem prądu\. To narzędzie, które rozwiązuje trzy problemy naraz: odpady, energię, nawożenie\.': 'We believe that a <span className="italic">biogas plant</span> is not just a source of electricity. It is a tool that solves three problems at once: waste, energy, fertilization.',
    r'Rolnictwo, które kiedyś żywiło naród, dziś jest oskarżane o emisję metanu, smród gnojowicy, wyjałowienie gleby\. Niesłusznie\. Wystarczy zamknąć obieg\.': 'Agriculture, which once fed the nation, is today accused of methane emissions, slurry stench, and soil depletion. Unjustly. It is enough to close the loop.',
    r'<span className="font-serif italic text-\[\#C6A87C\]">Każda</span> tona obornika to nie problem — to 60 m³ biogazu, 0\.13 MWh prądu, 22 kg potasu i fosforu wracającego do gleby zamiast jezior\. Wystarczy mieć narzędzia\.': '<span className="font-serif italic text-[#C6A87C]">Every</span> ton of manure is not a problem — it is 60 m³ of biogas, 0.13 MWh of electricity, 22 kg of potassium and phosphorus returning to the soil instead of lakes. You just need the tools.',
    r'Naszą rolą jest dostarczyć te narzędzia w jakości, w której nic się nie psuje przez 25 lat\. Stal nierdzewna 1\.4571\. Beton W10 XA3\. Silniki Tier-1\. Sterowniki ABB\. Bez compromises na specyfikacji materiałowej\.': 'Our role is to provide these tools with a quality where nothing breaks for 25 years. Stainless steel 1.4571. Concrete W10 XA3. Tier-1 engines. ABB controllers. Zero compromises on material specification.',
    r'Bo energia rolnicza nie zasługuje na mniej\.': 'Because agricultural energy deserves no less.',
    r'Założyciele': 'Founders',
    r'Warszawa': 'Warsaw',
    r'10\. maja 2026': 'May 10, 2026',
    r'Kukurydza': 'Corn',
    r'Wiosna\. 12 tysięcy nasion na hektar\. Każda łodyga to przyszłe 0\.4 m³ biogazu\.': 'Spring. 12 thousand seeds per hectare. Every stalk is a future 0.4 m³ of biogas.',
    r'W pierwszym roku współpracy mierzymy nie tylko areał — mierzymy słońce, deszcz i pH gleby\. Polska kukurydza energetyczna ma jedne z najwyższych w Europie potencjałów metanowych: 210 m³ biogazu z tony świeżej masy\.': 'In the first year of cooperation, we measure not only the acreage — we measure sun, rain, and soil pH. Polish energy corn has some of the highest methane potentials in Europe: 210 m³ of biogas from a ton of fresh mass.',
    r'Reaktor': 'Reactor',
    r'Cisza w której archeony pracują bez przerwy\.': 'Silence in which archaea work non-stop.',
    r'Kiszonka wjeżdża do dozownika o 6:00 rano\. Mieszadła obracają się wolno, 8 obrotów na minutę\. Bakterie metanogenne nie znoszą tlenu, hałasu, gwałtownych zmian\. To jest fabryka, w której najgłośniejszym dźwiękiem jest szum wentylatora chłodnicy\.': 'Silage enters the dispenser at 6:00 AM. Mixers rotate slowly, 8 revolutions per minute. Methanogenic bacteria cannot stand oxygen, noise, or sudden changes. This is a factory where the loudest sound is the roar of the cooler fan.',
    r'Sieć': 'Grid',
    r'Po 28 dniach biogaz przepływa przez ssawę silnika Tier-1\. 499 kW elektrycznych\.': 'After 28 days, biogas flows through the intake of the Tier-1 engine. 499 electrical kW.',
    r'Silnik Jenbacher J312 spala biogaz z dokładnością miliampera\. Energia trafia do krajowej sieci, sprzedawana w aukcjach OZE po cenie zakontraktowanej na 15 lat\. Każda godzina pracy to ok\. 550 zł brutto — niezależnie od pogody, pory roku, geopolityki\.': 'The Jenbacher J312 engine burns biogas with milliampere precision. Energy goes to the national grid, sold in RES auctions at a price contracted for 15 years. Every hour of operation is approx. 130 EUR gross — regardless of weather, season, or geopolitics.',
    r'Dom': 'Home',
    r'1 600 polskich gospodarstw domowych zasilanych z jednej biogazowni\. 24/7\.': '1,600 households powered by a single biogas plant. 24/7.',
    r'W odróżnieniu od wiatru i słońca — biogaz pracuje w nocy\. Pracuje w grudniu\. Pracuje, gdy giełda energii skoczy do 1500 zł/MWh w mroźny wieczór\. Tu nie ma kryzysu energetycznego — bo źródło rośnie na sąsiednim polu\.': 'Unlike wind and solar — biogas works at night. It works in December. It works when the energy exchange jumps to 400 EUR/MWh on a frosty evening. There is no energy crisis here — because the source grows in the neighboring field.',
    r'Powrót': 'Return',
    r'Poferment wraca na pole\. 30 ton dziennie pełnowartościowego nawozu NPK — zamknięcie obiegu\.': 'Digestate returns to the field. 30 tons daily of full-value NPK fertilizer — closing the loop.',
    r'To, co wyszło z gleby jako kukurydza, wraca jako nawóz\. Bez nasion chwastów, bez patogenów, bez smrodu\. Polski rolnik przestaje kupować mocznik i fosforany — bo wytwarza je sam, w swojej fabryce metanu\.': 'What came out of the soil as corn returns as fertilizer. Without weed seeds, without pathogens, without stench. The farmer stops buying urea and phosphates — because he produces them himself, in his own methane factory.',
    r'Sekwencja narracyjna — 5 rozdziałów': 'Narrative sequence — 5 chapters',
    r'Z pola <br/>': 'From the field <br/>',
    r'do prądu\.': 'to power.',
    r'Pięć rozdziałów\. Jeden obieg\. Setki kilometrów kabli, tysiące archeonów, dwa pokolenia rolników\.': 'Five chapters. One loop. Hundreds of kilometers of cables, thousands of archaea, two generations of farmers.',
    r'Liczba rozdziału': 'Chapter number',
    r'Cisza nocna': 'Night silence',
    r'Reaktor pracuje w trybie podtrzymania\. Mieszadła wolne — 4 obr/min\. Temperatura stała 38\.4 °C\.': 'Reactor operates in maintenance mode. Mixers slow — 4 rpm. Constant temperature 38.4 °C.',
    r'Pik gazowy': 'Gas peak',
    r'Maksymalna produkcja CH₄\. CHP Efficiency osiąga 44\.2%\. Tłoczenie do sieci na pełnej mocy\.': 'Maximum CH₄ production. CHP Efficiency reaches 44.2%. Pumping to the grid at full power.',
    r'Kontrola operatora': 'Operator control',
    r'Wizyta technika\. Pobór próbki do laboratorium\. Sprawdzenie szczelności gazu\.': 'Technician visit. Taking a sample to the lab. Gas tightness check.',
    r'Dozowanie popołudniowe': 'Afternoon dosing',
    r'Druga porcja substratu: 16 t\. Stabilizacja procesu\. Sonda lambda potwierdza skład\.': 'Second portion of substrate: 16 t. Process stabilization. Lambda probe confirms composition.',
    r'Najwyższe ceny energii w godzinach 18-21\. Algorytm SCADA maksymalizuje wyjście\.': 'Highest energy prices between 6-9 PM. SCADA algorithm maximizes output.',
    r'Powolne wytracanie mocy\. Mieszadła zwalniają\. Sieć przechodzi w noc\.': 'Slow power dissipation. Mixers slow down. The grid transitions into the night.',
    r'Jeden cykl\. 7 punktów krytycznych\. Algorytm, który pracuje, gdy ty śpisz\.': 'One cycle. 7 critical points. An algorithm that works while you sleep.',
    r'Archeon o nieregularnym kształcie wielokątnym\. Produkuje 70% metanu w reaktorze, rozkładając octan na CH₄ i CO₂\. Optimum pH 6\.8–7\.4\.': 'An archaeon with an irregular polygonal shape. Produces 70% of methane in the reactor, decomposing acetate into CH₄ and CO₂. Optimum pH 6.8–7.4.',
    r'Pałeczka długości 2–8 µm\. Wykorzystuje wodór i CO₂ do produkcji metanu\. Niezbędny w fazie wstępnej, gdy dominują wolne kwasy tłuszczowe\.': 'A rod 2–8 µm long. Uses hydrogen and CO₂ to produce methane. Essential in the initial phase when free fatty acids dominate.',
    r'Beztlenowiec rozkładający celulozę i hemicelulozę\. Pierwszy szczebel łańcucha pokarmowego w reaktorze\. Pracuje wydajnie w procesie mezofilowym \(38 °C\)\.': 'An anaerobe that breaks down cellulose and hemicellulose. The first rung of the food chain in the reactor. Works efficiently in the mesophilic process (38 °C).',
    r'Beztlenowa pałeczka G\(-\)\. Przekształca cukry proste w lotne kwasy tłuszczowe \(LKT\) — paliwo dla metanogenów\.': 'Anaerobic Gram-negative rod. Converts simple sugars into volatile fatty acids (VFA) — fuel for methanogens.',
    r'W jednej kropli substratu pracuje 10⁹ komórek\. Bakterie i archeony to nasi prawdziwi inżynierowie — wybieramy najefektywniejsze szczepy, dostosowane do polskiej diety reaktora\.': '10⁹ cells work in one drop of substrate. Bacteria and archaea are our true engineers — we select the most efficient strains, adapted to the local reactor diet.',
    r'Biogazownie rolnicze mają w Polsce wielki potencjał': 'Agricultural biogas plants have great potential in Poland',
    r'Rynek': 'Market',
    r'Od 2026 r\. polskie firmy i domy może zasilać błękitne paliwo': 'From 2026, Polish companies and homes may be powered by blue fuel',
    r'Analiza': 'Analysis',
    r'Biometan w Polsce\. Ocena potencjału \(Raport\)': 'Biomethane in Poland. Potential Assessment (Report)',
    r'Raport': 'Report',
    r'Nowe odmiany kukurydzy na ziarno, kiszonkę i biogaz': 'New varieties of corn for grain, silage, and biogas',
    r'Edukacja': 'Education',
    r'Analiza BMP \+ studium wykonalności': 'BMP Analysis + feasibility study',
    r'Pozwolenia \+ KIP \+ decyzja środowiskowa': 'Permits + PIS + environmental decision',
    r'Wylewki żelbetowe komór': 'Reinforced concrete pouring of chambers',
    r'Instalacja membran EPDM \+ zbiorników': 'Installation of EPDM membranes + tanks',
    r'Montaż CHP \+ układów pomp': 'CHP assembly + pump systems',
    r'Instalacja SCADA \+ sieć energetyczna': 'SCADA installation + power grid',
    r'Inokulacja \+ napełnianie startowe': 'Inoculation + start-up filling',
    r'Standardowy projekt biogazowni 0\.5 MW\. 11 faz, 14 miesięcy, 3 kategorie wykonawcze\. Bez poślizgów — zabezpieczone karami kontraktowymi\.': 'Standard 0.5 MW biogas plant design. 11 phases, 14 months, 3 execution categories. No delays — secured by contractual penalties.',
    r'Eksploatacja': 'Operation',
    r'COD — pełna moc operacyjna': 'COD — full operational power',
    r'Węgiel': 'Coal',
    r'Słońce': 'Solar',
    r'Biogaz nie jest najtańszy\. Nie jest najmniej powierzchniochłonny\. Jest jedyny, który łączy stabilność z ujemnym śladem węglowym\.': 'Biogas is not the cheapest. It is not the most space-saving. It is the only one that combines stability with a negative carbon footprint.',
    r'Forum Energii 2025, IEA World Energy Outlook 2024, dane branżowe sektora biogazu rolniczego w UE\. Wartości uśrednione dla projektu 0\.5 MW\.': 'Energy Forum 2025, IEA World Energy Outlook 2024, industry data of the agricultural biogas sector in the EU. Averaged values for a 0.5 MW project.',
    r'Biogazownia nie tylko nie emituje — utylizuje metan, który i tak wydostałby się z gnojowicy do atmosfery\. Stąd −25 g/kWh\.': 'A biogas plant not only does not emit — it utilizes methane that would escape from slurry into the atmosphere anyway. Hence −25 g/kWh.',
    r'Przychodu z pofermentu, kosztu utylizacji gnojowicy, niezależności energetycznej, wpływu na lokalne rolnictwo\. To zmieniłoby równanie\.': 'Digestate revenue, slurry disposal costs, energy independence, impact on local agriculture. This would change the equation.',
    r'Europejska dyrektywa regulująca urządzenia w strefach zagrożonych wybuchem\. Wszystkie elementy reaktora pracujące z metanem klasyfikowane są jako EX zone 1 lub 2\.': 'European directive regulating equipment in potentially explosive atmospheres. All reactor elements working with methane are classified as EX zone 1 or 2.',
    r'Test laboratoryjny mierzący maksymalny uzysk metanu z danej biomasy\. Trwa 30–60 dni\. Podstawa do każdej decyzji projektowej\.': 'Laboratory test measuring maximum methane yield from a given biomass. Lasts 30–60 days. The basis for every design decision.',
    r'Skojarzona produkcja energii elektrycznej i cieplnej\. Sprawność całkowita do 90% — w przeciwieństwie do 35% przy samym prądzie\.': 'Combined production of electricity and heat. Total efficiency up to 90% — contrary to 35% with power alone.',
    r'Dyspozycyjność': 'Availability factor',
    r'Procent czasu, w którym instalacja jest gotowa do pracy\. GP zapewnia 98% — ok\. 8 600 godzin rocznie\.': 'Percentage of time the installation is ready to operate. GP provides 98% — approx. 8,600 hours per year.',
    r'Model kontraktowy "pod klucz"\. Wykonawca odpowiada za projekt, dostawy i realizację inwestycji, dostarczając gotową instalację z celem uzysku\.': 'Turnkey contract model. The contractor is responsible for the design, procurement, and execution of the investment, delivering a ready installation with a yield goal.',
    r'Fermentacja mezofilowa': 'Mesophilic digestion',
    r'Process fermentacji w temperaturze 35–40 °C\. Najczęściej stosowany — kompromis między tempem rozkładu a stabilnością mikrobiomu\.': 'Fermentation process at 35–40 °C. Most commonly used — a compromise between decomposition rate and microbiome stability.',
    r'Siarkowodór': 'Hydrogen sulfide',
    r'Toksyczny gaz korozyjny\. Przekroczenie limitów \(np\. powyżej 200 ppm\) grozi uszkodzeniem silnika CHP\.': 'Toxic corrosive gas. Exceeding limits (e.g., above 200 ppm) risks damaging the CHP engine.',
    r'Karta Informacyjna Przedsięwzięcia': 'Project Information Sheet',
    r'Pierwszy dokument urzędowy w procesie pozyskiwania pozwolenia środowiskowego\. Zawiera lokalizację, technologię, planowane emisje\.': 'The first official document in the environmental permit acquisition process. Contains location, technology, planned emissions.',
    r'Lotne Kwasy Tłuszczowe': 'Volatile Fatty Acids',
    r'Produkty pośrednie fermentacji\. Ich nadmiar \(limit ok\. 3-4 g/L\) sygnalizuje zaburzenie procesu — tzw\. kwasicę reaktora\.': 'Intermediate fermentation products. Their excess (limit approx. 3-4 g/L) signals a process disturbance — so-called reactor acidosis.',
    r'Ostatnia faza fermentacji beztlenowej\. Archeony przekształcają octan i wodór w metan i dwutlenek węgla\. Sercem biznesu jest właśnie ta faza\.': 'The final phase of anaerobic fermentation. Archaea transform acetate and hydrogen into methane and carbon dioxide. The heart of the business is this very phase.',
    r'Odnawialne Źródła Energii': 'Renewable Energy Sources',
    r'Polski system wsparcia obejmujący aukcje i taryfy wsparcia \(FIT\)\. Biogaz rolniczy ma własny koszyk — bez konkurencji z wiatrem i słońcem\.': 'Support system including auctions and feed-in tariffs (FIT). Agricultural biogas has its own basket — no competition with wind and solar.',
    r'Produkt uboczny fermentacji\. Bezzapachowy, bogaty w azot, fosfor, potas\. Zastępuje syntetyczne nawozy\. 30 ton dziennie z 0\.5 MW\.': 'Fermentation byproduct. Odorless, rich in nitrogen, phosphorus, potassium. Replaces synthetic fertilizers. 30 tons daily from 0.5 MW.',
    r'System nadzoru, kontroli i akwizycji danych\. Tysiące zmiennych na sekundę\. Algorytm sterujący każdym zaworem, każdą pompą\.': 'Supervisory control and data acquisition system. Thousands of variables per second. An algorithm controlling every valve, every pump.',
    r'Urząd Dozoru Technicznego': 'Office of Technical Inspection',
    r'Polski organ regulacyjny nadzorujący zbiorniki ciśnieniowe, rurociągi i urządzenia poddozorowe\. Każda biogazownia podlega corocznym kontrolom\.': 'Regulatory body supervising pressure vessels, pipelines, and supervised equipment. Every biogas plant is subject to annual inspections.',
    r'Każda branża ma swój język\. Tutaj 14 terminów, które oddzielają inżyniera od dyletanta\. Czyta się jak Encyklopedię Britannica\.': 'Every industry has its language. Here are 14 terms that separate an engineer from a dilettante. Reads like the Encyclopaedia Britannica.',
    r'Konstrukcja nośna': 'Load-bearing structure',
    r'Beton hydrotechniczny o szczelności gazowej P10\. 28-dniowa wytrzymałość na ściskanie 45 MPa\. Zbrojony stalą rebariową BSt 500 S\.': 'Hydrotechnical concrete with P10 gas tightness. 28-day compressive strength 45 MPa. Reinforced with BSt 500 S rebar.',
    r'PL · Górażdże': 'EU · Górażdże',
    r'Austenityczna stal kwasoodporna z dodatkiem tytanu\. Odporność na H₂S, NH₃ i lotne kwasy tłuszczowe\. Spawana metodą TIG w atmosferze argonu\.': 'Austenitic acid-resistant steel with titanium addition. Resistance to H₂S, NH₃, and volatile fatty acids. TIG welded in an argon atmosphere.',
    r'Dwuwarstwowa membrana podwójna\. Górna magazynuje biogaz, dolna chroni przed wnikaniem tlenu\. Żywotność 25 lat w warunkach polskich\.': 'Double-layer membrane. The upper stores biogas, the lower protects against oxygen ingress. 25-year lifespan.',
    r'Miedź Cu-DHP': 'Copper Cu-DHP',
    r'Wymienniki ciepła': 'Heat exchangers',
    r'Miedź beztlenowa wysokoprzewodząca\. Przewodność cieplna 380 W/m·K\. Wymienniki płytowe Alfa Laval do odzysku ciepła ze spalin CHP\.': 'Oxygen-free high-conductivity copper. Thermal conductivity 380 W/m·K. Alfa Laval plate heat exchangers for heat recovery from CHP exhaust gases.',
    r'Beton z Górażdży\. Stal z Tornio\. Membrana z Grazu\. Miedź z Linköping\. Cztery materiały, które razem ważą 320 ton i przetrwają 25 polskich zim\.': 'Concrete from Górażdże. Steel from Tornio. Membrane from Graz. Copper from Linköping. Four materials that together weigh 320 tons and will survive 25 winters.',
    r'PRÓBKA NR': 'SAMPLE NO',
    r'PROJEKT · NADZÓR · OPTYMALIZACJA · SERWIS ·': 'DESIGN · SUPERVISION · OPTIMIZATION · SERVICE ·',
    r'CH₄ \+ CO₂ → CZYSTY KAPITAŁ · CH₄ \+ CO₂ → CZYSTY KAPITAŁ ·': 'CH₄ + CO₂ → PURE CAPITAL · CH₄ + CO₂ → PURE CAPITAL ·',
    r'jak mleko, zboże, mięso\.': 'like milk, grain, meat.',
    r'Ustawa o biokomponentach': 'Biocomponents Act',
    r'Pierwsze regulacje prawne tworzące ramę dla produkcji energii z biogazu rolniczego w Polsce\.': 'The first legal regulations creating a framework for energy production from agricultural biogas.',
    r'Zielone certyfikaty': 'Green certificates',
    r'Wprowadzenie systemu wsparcia kogeneracji odnawialnej\. Powstają pierwsze biogazownie rolnicze 0\.5–1 MW\.': 'Introduction of a support system for renewable cogeneration. The first 0.5–1 MW agricultural biogas plants are built.',
    r'Pierwsza setka instalacji': 'The first hundred installations',
    r'Liczba czynnych biogazowni rolniczych w Polsce przekracza 30\. Dominują projekty oparte o kiszonkę kukurydzy\.': 'The number of active agricultural biogas plants exceeds 30. Projects based on corn silage dominate.',
    r'Ustawa OZE — aukcje': 'RES Act — auctions',
    r'Wprowadzenie systemu aukcyjnego\. Biogaz rolniczy zyskuje osobny koszyk kontraktowy bez konkurencji z wiatrem i słońcem\.': 'Introduction of the auction system. Agricultural biogas gains a separate contracting basket without competition from wind and solar.',
    r'Dyrektywa RED II': 'RED II Directive',
    r'Unia definiuje kryteria zrównoważonego rozwoju dla bioenergii\. Każdy m³ biogazu wymaga dokumentacji pochodzenia biomasy\.': 'The Union defines sustainability criteria for bioenergy. Every m³ of biogas requires documentation of biomass origin.',
    r'Pakiet Fit for 55': 'Fit for 55 Package',
    r'Nacisk na biometan i biogazownie komunalne\. Otwarcie nowych ścieżek finansowych w ramach Krajowego Planu Odbudowy\.': 'Emphasis on biomethane and municipal biogas plants. Opening of new financial paths under the National Recovery Plan.',
    r'Strategia biometanu': 'Biomethane strategy',
    r'Polski rząd publikuje strategię docelową — 250 biogazowni do 2030 r\., 4 mld m³ biometanu rocznie\.': 'Target strategy published — 250 biogas plants by 2030, 4 billion m³ of biomethane annually.',
    r'Boom inwestycyjny': 'Investment boom',
    r'Liczba projektów w pozwoleniach na budowę przekracza 180\. BGK, BOŚ i EBOiR uruchamiają dedykowane linie finansowe\.': 'The number of projects in building permits exceeds 180. BGK, BOŚ and EBRD launch dedicated financial lines.',
    r'Tu jesteśmy': 'We are here',
    r'Wchodzimy na rynek z jednym mandatem: industrializacja procesu\. Biogazownia jako produkt powtarzalny, projektowany do tych samych norm co rafineria — nie eksperyment\.': 'We enter the market with one mandate: industrialization of the process. A biogas plant as a repeatable product, designed to the same standards as a refinery — not an experiment.',
    r'Dziewięć kamieni milowych\. Trzy ustawy krajowe, dwie dyrektywy unijne, jeden trend wzrostowy\. Tak dojrzewała branża biogazu rolniczego w Polsce\.': 'Nine milestones. Three national laws, two EU directives, one upward trend. This is how the agricultural biogas industry matured.',
    r'Wszystkie wymiary w mm chyba że zaznaczono inaczej\.': 'All dimensions in mm unless otherwise noted.',
    r'Tolerancja wymiarowa wg ISO 2768-mK dla wymiarów liniowych\.': 'Dimensional tolerance acc. to ISO 2768-mK for linear dimensions.',
    r'Powłoki antykorozyjne — system C5 wg ISO 12944\.': 'Anticorrosion coatings — C5 system acc. to ISO 12944.',
    r'Próba szczelności gazowej przed odbiorem UDT — nadciśnienie 50 mbar / 24h\.': 'Gas tightness test before UDT acceptance — 50 mbar / 24h overpressure.',
    r'Strefy zagrożone wybuchem — klasyfikacja wg PN-EN 60079-10-1\.': 'Explosive atmospheres — classification acc. to EN 60079-10-1.',
    r'Uziemienie ekwipotencjalne wszystkich elementów metalowych — rezystancja < 10 Ω\.': 'Equipotential bonding of all metal elements — resistance < 10 Ω.',
    r'Sprawdzenie szczelności silnika lambdą — interwał 200 mth\.': 'Engine tightness check with lambda — 200 mth interval.',
    r'Pojemność 900 t\. Geomembrana EPDM\.': 'Capacity 900 t. EPDM geomembrane.',
    r'Faza wstępna\. Mezofile 38 °C\.': 'Initial phase. Mesophiles 38 °C.',
    r'Faza właściwa\. Czas retencji 28 dni\.': 'Main phase. Retention time 28 days.',
    r'Membrana podwójna 600 m³\.': 'Double membrane 600 m³.',
    r'Standardowa biogazownia 0\.5 MW na 1\.2 hektarze\. 10 obiektów, 320 metrów rurociągów, 3 kilometry kabli sterowniczych\. Każdy element ma swoje miejsce — i swój dokument\.': 'Standard 0.5 MW biogas plant on 1.2 hectares. 10 facilities, 320 meters of pipelines, 3 kilometers of control cables. Every element has its place — and its document.',
    r'Środowisko': 'Environment',
    r'Board of Directorszanie środowiskowe': 'Environmental management',
    r'Jakość': 'Quality',
    r'System zarządzania jakością': 'Quality management system',
    r'Zgodność': 'Compliance',
    r'BHP': 'OHS',
    r'Bezpieczeństwo pracy': 'Occupational safety',
    r'Dyrektywa': 'Directive',
    r'Wybuchowość': 'Explosiveness',
    r'Strefy zagrożone wybuchem': 'Explosive atmospheres',
    r'Wymóg': 'Requirement',
    r'Dozór UDT': 'Technical Inspection',
    r'Zbiorniki ciśnieniowe': 'Pressure vessels',
    r'Norma': 'Standard',
    r'Spawalnictwo': 'Welding',
    r'Kwalifikacja procesów spawania': 'Welding process qualification',
    r'Powłoki': 'Coatings',
    r'Antykorozja C5': 'Anticorrosion C5',
    r'Każdy projekt projektujemy do ośmiu zewnętrznych norm\. Nie wymieniamy ich dla marketingu — wymieniamy, bo definiują zakres odpowiedzialności wobec inwestora i organów dozoru\.': 'We design every project to eight external standards. We do not list them for marketing — we list them because they define the scope of responsibility towards the investor and supervisory bodies.',
    r'Inżynier nie wierzy w „prawie szczelne"\. Inżynier mierzy\.': 'An engineer doesn\'t believe in "almost tight". An engineer measures.',
    r'Pierwsza zasada konstrukcyjna': 'First design principle',
    r'Każda biogazownia jest tak dobra jak najsłabsza spawa\. Każdą sprawdzamy testem nieniszczącym\.': 'Every biogas plant is only as good as its weakest weld. We check each one with a non-destructive test.',
    r'Dział kontroli jakości': 'Quality control department',
    r'Bakterie metanogenne nie negocjują\. Ani ceny prądu, ani warunków pogodowych\. Pracują 24/7\.': 'Methanogenic bacteria do not negotiate. Neither electricity prices nor weather conditions. They work 24/7.',
    r'Dział biologii': 'Biology department',
    r'Pojemność reaktora I \+ II': 'Reactor I + II capacity',
    r'Średnica każdej komory': 'Diameter of each chamber',
    r'Wysokość konstrukcji': 'Construction height',
    r'Grubość ścian żelbetowych': 'Reinforced concrete wall thickness',
    r'Powierzchnia działki min\.': 'Plot area min.',
    r'Wsad dobowy': 'Daily feedstock',
    r'Sprawność elektryczna CHP': 'CHP electrical efficiency',
    r'Sprawność termiczna': 'Thermal efficiency',
    r'Sprawność całkowita': 'Total efficiency',
    r'Wymagania środowiskowe': 'Environmental requirements',
    r'Hałas \(granica działki\) max': 'Noise (plot boundary) max',
    r'Wykorzystanie odpadów': 'Waste utilization',
    r'NAPĘDY & SILNIKI': 'DRIVES & MOTORS',
    r'DYNAMIKA PŁYNÓW': 'FLUID DYNAMICS',
    r'Green Plant Tech to nowy podmiot, ale nie uczymy się na błędach inwestora\. Nasz zespół wnosi ponad 50 lat skumulowanego doświadczenia z projektów infrastrukturalnych w Europie\.': 'Green Plant Tech is a new entity, but we do not learn from the investor\'s mistakes. Our team brings over 50 years of accumulated experience from infrastructure projects in Europe.',
    r'Umów wstępny audyt technologiczny\. Weryfikujemy potencjał Twojego zakładu i szacujemy bazowy CAPEX\.': 'Schedule an initial technological audit. We verify the potential of your facility and estimate the base CAPEX.',
    r'Wyślij formularz': 'Send form'
}

for k, v in replacements.items():
    content = re.sub(k, v, content, flags=re.IGNORECASE)

with open("greenplant_en.jsx", "w", encoding="utf-8") as f:
    f.write(content)
