import re
import os

def replace_in_file(file_path, replacements):
    if not os.path.exists(file_path):
        return
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    for old, new in replacements.items():
        content = re.sub(re.escape(old), new, content)
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

# Massive clean-up for presentation_en.html
html_massive_replacements = {
    'Dla instalacji mikro (< 0,5 MW) ścieżka administracyjna bywa prostsza niż dla dużych projektów.': 'For micro-installations (< 0.5 MW), the administrative path is often simpler than for large projects.',
    'razem z nią.': 'together with it.',
    'Większa część wartości zostaje w regionie: u rolników, wykonawców i lokalnych usługodawców.': 'Most of the value stays in the region: with farmers, contractors, and local service providers.',
    'Mechanizm FIT/FIP stabilizuje cenę energii nawet do 15 years, a OSD realizuje obowiązek zakupu zgodnie z warunkami wsparcia.': 'The FIT/FIP mechanism stabilizes energy prices for up to 15 years, and the DSO fulfills the purchase obligation according to the support conditions.',
    'Programy KOWR i ARiMR wspierają inwestycje rolnicze w biogaz and infrastrukturę towarzyszącą.': 'KOWR and ARiMR programs support agricultural investments in biogas and accompanying infrastructure.',
    'Projekt jest prowadzony tak, by chronić bieżące dopłaty i jednocześnie otwierać dodatkowe źródła finansowania.': 'The project is managed to protect current subsidies and simultaneously open additional funding sources.',
    'Płatności bezpośrednie (WPR/CAP) — bez zmian': 'Direct payments (CAP) — no changes',
    'Skąd Płyną <span class="serif-italic text-gold-accent">Pieniądze.</span>': 'Where the <span class="serif-italic text-gold-accent">Money Flows From.</span>',
    'Instalacja pracuje równolegle do gospodarstwa i stabilizuje rytm pracy przez cały rok.': 'The installation operates parallel to the farm and stabilizes the work rhythm throughout the year.',
    'Brak decyzji także kosztuje. Poniżej porównanie ciężaru pozostania przy obecnym modelu vs. wejście w biogaz.': 'Lack of decision also costs. Below is a comparison of the burden of staying with the current model vs. entering biogas.',
    'Produkcja prądu i ciepła na miejscu — rachunki mogą spaść znacząco': 'On-site power and heat production — bills can drop significantly.',
    'Nie jesteś dzierżawcą ani klientem. Jesteś udziałowcem SPV, a wypracowana wartość zostaje w gospodarstwie.': 'You are not a lessee or a customer. You are an SPV shareholder, and the generated value stays on the farm.',
    'SPV produkuje prąd, HEAT i poferment. Projekt pracuje od rozruchu, a udziały pozostają po Twojej stronie.': 'SPV produces electricity, heat, and digestate. The project works from startup, and the shares remain on your side.',
    'Najczęstsze pytania, które słyszymy podczas wizyt w gospodarstwach i spotkaniach lokalnych.': 'The most common questions we hear during farm visits and local meetings.',
    'Instalacja zajmuje ~0,7 ha (ok. 0,4% przy 180 ha). Reszta pól pracuje normalnie — a nawet lepiej dzięki pofermentowi.': 'The installation occupies ~0.7 ha (approx. 0.4% at 180 ha). The rest of the fields work normally — and even better thanks to the digestate.',
    'Tak. Umowa SPV przewiduje klauzule zbycia udziałów — możesz je sprzedać or przekazać dzieciom jako gotowy majątek.': 'Yes. The SPV agreement provides for share disposal clauses — you can sell them or pass them on to your children as ready assets.',
    'większy zysk</strong> z hektara niż przy sprzedaży.': 'higher profit</strong> per hectare than from sale.',
    'Dodatkowo:</strong> miks z własną gnojowicą może ograniczać koszt dokupowanego wsadu.': 'Additionally:</strong> mixing with your own slurry can reduce the cost of purchased feedstock.',
    'Pieniądze.': 'Money.',
    'SĄSIEDZI': 'NEIGHBORS',
    'POLSKI POTENCJAŁ': 'POLISH POTENTIAL',
    'POFERMENT SZCZEGÓŁOWY': 'DETAILED DIGESTATE',
    'DOPŁATY I SUBSYDIA': 'SUBSIDIES AND GRANTS',
    'STRUMIENIE PRZYCHODÓW': 'REVENUE STREAMS',
    'CO JEŚLI NIE?': 'WHAT IF NOT?',
    'SĄSIAD': 'NEIGHBOR',
    'Wysłodki': 'Beet pulp',
    'buraczane → fermentor': 'beet pulp → fermenter',
    'podatki': 'taxes',
    'lokalne': 'local',
    'gminie': 'municipality',
    'bezpośrednie': 'direct',
    'zmian': 'changes',
    'spotkań': 'meetings',
    'lokalnych': 'local',
    'zbycia': 'disposal',
    'udziałów': 'shares',
    'sprzedać': 'sell',
    'przekazać': 'hand over',
    'dzieciom': 'children',
    'gotowy': 'ready',
    'majątek': 'assets',
    'większy': 'larger',
    'zysk': 'profit',
    'sprzedaży': 'sale',
    'Dodatkowo': 'Additionally',
    'własną': 'own',
    'gnojowicą': 'slurry',
    'ograniczać': 'limit',
    'dokupowanego': 'purchased',
    'wsadu': 'feedstock',
    'Corn silage → tank': 'Corn silage → tank',
    'Płatności': 'Payments',
    'szacunkach': 'estimates',
    'branżowych': 'industry',
    'orientacyjne': 'approximate',
    'oparte': 'based',
    'Wartości': 'Values',
    'pracuje': 'works',
    'miesięczny': 'monthly',
    'momentu': 'moment',
    'rozruchu': 'startup',
    'Horyzont': 'Horizon',
    'wsparcia': 'support',
    'zwykle': 'usually',
    'systemu': 'system',
    'zależnie': 'depending',
    'przyszłości': 'future',
    'bezpiecznej': 'safe',
    'suwerenności': 'sovereignty',
    'lokalnej': 'local',
    'Większa': 'Greater',
    'część': 'part',
    'wartości': 'value',
    'zostaje': 'stays',
    'rolników': 'farmers',
    'wykonawców': 'contractors',
    'usługodawców': 'service providers',
    'stabilizuje': 'stabilizes',
    'cenę': 'price',
    'energii': 'energy',
    'nawet': 'even',
    'realizuje': 'realizes',
    'obowiązek': 'obligation',
    'zakupu': 'purchase',
    'zgodnie': 'according',
    'warunkami': 'conditions',
    'wspierają': 'support',
    'inwestycje': 'investments',
    'rolnicze': 'agricultural',
    'biogaz': 'biogas',
    'infrastrukturę': 'infrastructure',
    'towarzyszącą': 'accompanying',
    'chronić': 'protect',
    'bieżące': 'current',
    'dopłaty': 'subsidies',
    'jednocześnie': 'simultaneously',
    'otwierać': 'open',
    'dodatkowe': 'additional',
    'źródła': 'sources',
    'finansowania': 'financing',
    'równolegle': 'parallel',
    'gospodarstwa': 'farm',
    'rytm': 'rhythm',
    'pracy': 'work',
    'cały': 'whole',
    'rok': 'year',
    'własne': 'own',
    'pokosne': 'mowed',
    'Szczytowa': 'Peak',
    'produkcja': 'production',
    'prądu': 'electricity',
    'kukurydzy': 'corn',
    'zbiornik': 'tank',
    'fermentor': 'fermenter',
    'zimę': 'winter',
    'Przygotowanie': 'Preparation',
    'Roczne': 'Annual',
    'rozliczenie': 'settlement',
    'decyzji': 'decision',
    'kosztuje': 'costs',
    'porównanie': 'comparison',
    'ciężaru': 'burden',
    'pozostania': 'staying',
    'obecnym': 'current',
    'biogaz': 'biogas',
    'wejście': 'entering',
    'obowiązki': 'obligations',
    'Wymogi': 'Requirements',
    'kontrole': 'inspections',
    'wokół': 'around',
    'rosnąć': 'increase',
    'miejscu': 'place',
    'rachunki': 'bills',
    'mogą': 'can',
    'spaść': 'drop',
    'znacząco': 'significantly',
    'Największą': 'Greatest',
    'przewagę': 'advantage',
    'budują': 'build',
    'wchodzą': 'enter',
    'wcześniej': 'earlier',
    'dzierżawcą': 'lessee',
    'klientem': 'customer',
    'udziałowcem': 'shareholder',
    'wypracowana': 'generated',
    'wartość': 'value',
    'produkuje': 'produces',
    'poferment': 'digestate',
    'udziały': 'shares',
    'pozostają': 'remain',
    'stronie': 'side',
    'Najczęstsze': 'Most common',
    'pytania': 'questions',
    'słyszymy': 'we hear',
    'wizyt': 'visits',
    'spotkaniach': 'meetings',
    'zajmuje': 'occupies',
    'Reszta': 'Rest',
    'pól': 'fields',
    'normalnie': 'normally',
    'lepiej': 'better',
    'dzięki': 'thanks to',
    'pofermentowi': 'digestate',
    'umowa': 'agreement',
    'przewiduje': 'provides',
    'klauzule': 'clauses',
    'możesz': 'you can',
}

# Run massive replacements
replace_in_file('public/presentation_en.html', html_massive_replacements)

print("Massive translation fixes completed.")
