import re
import os

files = ["greenplant_en.jsx", "public/presentation_en.html"]

replacements = {
    r'Sekwencja <br/>\s*<span className="italic font-light text-\[\#C6A87C\]">Wdrożeniowa\.</span>': r'Implementation <br/><span className="italic font-light text-[#C6A87C]">Sequence.</span>',
    r'Macierz <br/>\s*<span className="italic text-\[\#C6A87C\] font-Standardl">Substratów\.</span>': r'Substrate <br/><span className="italic text-[#C6A87C] font-Standardl">Matrix.</span>',
    r'Kategoria Materiału': 'Material Category',
    r'Zawartość CH4': 'CH4 Content',
    r'Potencjał Energetyczny': 'Energy Potential',
    r'Węzeł <br/>\s*<span className="italic text-\[\#C6A87C\] font-Standardl">Systemowy\.</span>': r'System <br/><span className="italic text-[#C6A87C] font-Standardl">Node.</span>',
    r'Zautomatyzowana sprzedaż nadwyżek energii w oparciu o algorytmy Peak Shaving i spotowe ceny energii\.': 'Automated sale of surplus energy based on Peak Shaving algorithms and spot energy prices.',
    r'Redukcja kosztów operacyjnych poprzez zasilanie lokalnej infrastruktury darmową energią cieplną\.': 'Operational cost reduction by powering local infrastructure with free thermal energy.',
    r'Zamknięcie obiegu pierwiastków poprzez dystrybucję stabilizowanego, bezzapachowego pofermentu\.': 'Closing the elemental loop through the distribution of stabilized, odorless digestate.',
    r'Cyfrowy <br/>\s*<span className="text-\[\#C6A87C\] not-italic">bliźniak\.</span>': r'Digital <br/><span className="text-[#C6A87C] not-italic">twin.</span>',
    r'Nadzór <br/>\s*<span className="italic font-light text-\[\#C6A87C\]">Weryfikowany\.</span>': r'Verified <br/><span className="italic font-light text-[#C6A87C]">Supervision.</span>',
    r'Podgląd na żywo każdego zaworu i mieszadła\. Wykrywanie anomalii zanim staną się awarią\.': 'Live view of every valve and mixer. Anomaly detection before they become failures.',
    r'Cotygodniowa Analysis parametrów fermentacji\. Optymalizacja diety Reactora\.': 'Weekly analysis of fermentation parameters. Reactor diet optimization.',
    r'Autoryzowany serwis agregatów CHP i systemów pompujących\. Oryginalne części\.': 'Authorized service for CHP units and pumping systems. Original parts.',
    r'Bezpieczeństwo <br/>\s*<span className="italic text-\[\#C6A87C\] font-Standardl">Standardtywne\.</span>': r'Standard <br/><span className="italic text-[#C6A87C] font-Standardl">Safety.</span>',
    r'Zasięg <br/>\s*<span className="italic text-\[\#C6A87C\] font-Standardl">operacyjny\.</span>': r'Operational <br/><span className="italic text-[#C6A87C] font-Standardl">reach.</span>',
    r'Złożono krojem': 'Typeset in',
    r'oraz': 'and',
    r'DWG-014 / PRZEKRÓJ A-A': 'DWG-014 / CROSS SECTION A-A',
    r'była przywilejem <span className="italic text-\[\#C6A87C\]">miast</span>,<br/>': 'was a privilege of <span className="italic text-[#C6A87C]">cities</span>,<br/>',
    r'<span className="italic text-\[\#C6A87C\]">elektrownią\.</span>': '<span className="italic text-[#C6A87C]">power plant.</span>',
    r'Województwa — gęstość rynku': 'Provinces — market density',
    r'W pierwszym roku współpracy mierzymy nie tylko areał — mierzymy Solar, deszcz i pH gleby\. Polska Corn energetyczna ma jedne z najwyższych w Europie potencjałów metanowych: 210 m³ biogazu z tony świeżej masy\.': 'In the first year of cooperation, we measure not only the acreage — we measure sun, rain, and soil pH. Polish energy corn has some of the highest methane potentials in Europe: 210 m³ of biogas from a ton of fresh mass.',
    r'To, co wyszło z gleby jako Corn, wraca jako nawóz\. Bez nasion chwastów, bez patogenów, bez smrodu\. Polski rolnik przestaje kupować mocznik i fosforany — bo wytwarza je sam, w swojej fabryce metanu\.': 'What sprang from the soil as corn returns as fertilizer. Free from weed seeds, pathogens, and odors. The farmer stops buying urea and phosphates—because he produces them himself in his own methane factory.',
    r'Reactor pracuje w trybie podtrzymania\. Mieszadła wolne — 4 obr/min\. Temperatura stała 38\.4 °C\.': 'The reactor operates in maintenance mode. Mixers run slowly at 4 rpm. Constant temperature of 38.4 °C.',
    r'Powolne wytracanie mocy\. Mieszadła zwalniają\. Grid przechodzi w noc\.': 'Slow power dissipation. Mixers slow down. The grid transitions into the night.',
    r'Dwadzieścia cztery <br/>\s*<span className="italic text-\[\#C6A87C\] font-Standardl">godziny\.</span>': r'Twenty-four <br/><span className="italic text-[#C6A87C] font-Standardl">hours.</span>',
    r'Archeon o nieregularnym kształcie wielokątnym\. Produkuje 70% metanu w Reactorze, rozkładając octan na CH₄ i CO₂\. Optimum pH 6\.8–7\.4\.': 'An irregularly shaped polygonal archaeon. It produces 70% of the reactor\'s methane by decomposing acetate into CH₄ and CO₂. Optimal pH is 6.8–7.4.',
    r'Pałeczka długości 2–8 µm\. Wykorzystuje wodór i CO₂ do produkcji metanu\. Niezbędny w fazie wstępnej, gdy Homeinują wolne kwasy tłuszczowe\.': 'A rod-shaped bacterium 2–8 µm in length. It uses hydrogen and CO₂ to produce methane. Essential during the initial phase when free fatty acids dominate.',
    r'Beztlenowiec rozkładający celulozę i hemicelulozę\. Pierwszy szczebel łańcucha pokarmowego w Reactorze\. Pracuje wydajnie w procesie mezofilowym \(38 °C\)\.': 'An anaerobe that breaks down cellulose and hemicellulose. It forms the first rung of the reactor\'s food chain and operates highly efficiently in mesophilic conditions (38 °C).',
    r'Taxonomia mikrobiologiczna — żywa kadra Reactora': 'Microbiological taxonomy — the living staff of the reactor',
    r'W jednej kropli substratu pracuje 10⁹ komórek\. Bakterie i archeony to nasi prawdziwi inżynierowie — wybieramy najefektywniejsze szczepy, dostosowane do polskiej diety Reactora\.': 'A billion cells operate in a single drop of substrate. Bacteria and archaea are our true engineers—we select the most efficient strains tailored specifically to the local reactor diet.',
    r'Od 2026 r\. polskie firmy i Homey może zasilać błękitne paliwo': 'From 2026, Polish companies and homes may be powered by blue fuel',
    r'Co warto śledzić w sektorze': 'What to track in the sector',
    r'Analysis BMP \+ studium wykonalności': 'BMP Analysis + feasibility study',
    r'Harmonogram — 14 miesięcy': 'Schedule — 14 months',
    r'Analysis porównawcza źródeł energii': 'Comparative energy source analysis',
    r'Cztery źródła, <br/>\s*<span className="italic text-\[\#C6A87C\] font-Standardl">jedno równanie\.</span>': r'Four sources, <br/><span className="italic text-[#C6A87C] font-Standardl">one equation.</span>',
    r'Źródło danych': 'Data source',
    r'Słownik <br/>\s*<span className="italic text-\[\#C6A87C\] font-Standardl">branżowy\.</span>': r'Industry <br/><span className="italic text-[#C6A87C] font-Standardl">glossary.</span>',
    r'Austenityczna stal kwasoodporna z dodatkiem tytanu\. Odporność na H₂S, NH₃ i Volatile Fatty Acids\. Spawana metodą TIG w atmosferze argonu\.': 'Austenitic acid-resistant steel with titanium. Resistant to H₂S, NH₃ and Volatile Fatty Acids. TIG welded in an argon atmosphere.',
    r'Z czego <br/>\s*<span className="italic text-\[\#C6A87C\] font-Standardl">to się składa\.</span>': r'What <br/><span className="italic text-[#C6A87C] font-Standardl">it consists of.</span>',
    r'Każdy kilogram, który wytworzymy w Reactorze, to kilogram, który nie wydostał się z gnojowicy do atmosfery\. To nie tylko energia — to <span className="text-\[\#C6A87C\] not-italic">utylizacja, która sama się amortyzuje</span>\.': 'Every kilogram we produce in the reactor is a kilogram that didn\'t escape from slurry into the atmosphere. It\'s not just energy — it\'s <span className="text-[#C6A87C] not-italic">utilization that pays for itself</span>.',
    r'Liczba czynnych biogazowni rolniczych w Polsce przekracza 30\. Homeinują projekty oparte o kiszonkę kukurydzy\.': 'The number of active agricultural biogas plants in Poland exceeds 30. Projects based on corn silage dominate.',
    r'Biogazownia rolnicza 0\.5 MW <br/>\s*<span className="italic text-\[\#C6A87C\]">— przekrój podłużny\.</span>': r'Agricultural biogas plant 0.5 MW <br/><span className="italic text-[#C6A87C]">— longitudinal section.</span>',
    r'— GRANICA DZIAŁKI — 12 800 m² —': '— PLOT BOUNDARY — 12 800 m² —',
    r'DZIAŁKA: 1\.28 ha': 'PLOT: 1.28 ha',
    r'⌗ Widok z góry 0° · Skala 1:1000': '⌗ Top view 0° · Scale 1:1000',
    r'Standards referencyjne — według czego projektujemy': 'Reference standards — what we design against',
    r'Trzy zasady · zapisane na ścianach': 'Three principles · written on the walls',
    r'— Źródło': '— Source',
    r'Pełna <br/>\s*<span className="italic text-\[\#C6A87C\] font-Standardl">specyfikacja\.</span>': r'Full <br/><span className="italic text-[#C6A87C] font-Standardl">specification.</span>',
    r'Dział technologiczny GP': 'GP Technology Department',
    r'Inżynieria <br/>\s*<span className="italic text-\[\#C6A87C\] font-Standardl">procesowa\.</span>': r'Process <br/><span className="italic text-[#C6A87C] font-Standardl">engineering.</span>',
    
    # presentation_en.html specifics
    r'Dlaczego koszt uprawy spada o 30 zł/t\?': 'Why does cultivation cost drop by 30 PLN/t?',
    r'Zastępując nim nawozy sztuczne, obniżasz bezpośrednie nakłady na hektar o ok\. 1 300 - 1 500 PLN\.': 'By replacing synthetic fertilizers, you reduce direct hectare outlays by approx. 1,300 - 1,500 PLN.',
    r'120 krów •': '120 cows •',
    r'Przychód SPV': 'SPV Revenue',
    r'PLN / rok \(sprzedaż energii, 4 100 MWh\)': 'PLN / year (energy sales, 4,100 MWh)',
    r'Nawóz \(Poferment\)': 'Fertilizer (Digestate)',
    r'kosztów nawożenia': 'fertilization costs',
    r'Energia Własna': 'Own Energy',
    r'prąd i ciepło': 'electricity and heat',
    r'Odór': 'Odor',
    r'redukcja zapachów': 'odor reduction',
    r'Zajętość Ziemi': 'Land Use',
    r'wysoka efektywność na małej powierzchni': 'high efficiency on a small footprint',
    r'Skalowalność': 'Scalability',
    r'możliwość rozbudowy': 'expansion potential',
    r'Przy pełnym wykorzystaniu pofermentu i odpowiednim bilansie składników dla gleby; poziom redukcji zapachów zależy od technologii i reżimu eksploatacji\.': '*With full digestate utilization and proper soil nutrient balance; odor reduction levels depend on technology and operational regime.',
    r'Green Plant pokrywa koszty napraw i serwisu zgodnie z umową operacyjną\. Certyfikat ATEX, podwójna membrana, pochodnia awaryjna\. Ubezpieczenie': 'Green Plant covers repair and service costs as per the operational agreement. ATEX certificate, double membrane, emergency flare. Insurance',
    r'System FIT/FIP \(Ustawa OZE\) zapewnia stałą cenę przez 15 lat\. <strong class="text-emerald-600">Coroczna waloryzacja o inflację \(CPI\)\.</strong>': 'The FIT/FIP system (RES Act) provides a fixed price for 15 years. <strong class="text-emerald-600">Annual inflation indexation (CPI).</strong>',
    r'Odpowiedzialność Prawna': 'Legal Liability',
    r'SPV to odrębny podmiot\. Twój majątek osobisty jest': 'SPV is a separate entity. Your personal assets are',
    r'roczny może być niższy, ale instalacja utrzymuje ciągłość pracy\.': 'annual may be lower, but the installation maintains operational continuity.',
    r'Bilans Odpowiedzialności': 'Liability Balance',
    r'Formalności': 'Formalities',
    r'Bezpłatna wizyta na substratów i przyłącza\.': 'Free visit for substrates and connection assessment.',
    r'środowiskowy, warunki zabudowy i uzgodnienia przyłączeniowe\.': 'environmental, zoning conditions, and connection agreements.',
    r'CZAS: DO 4 MIESIĘCY': 'TIME: UP TO 4 MONTHS',
    r'homeknięcie finansowania i instrumentów wsparcia \(częściowo równolegle z formalnościami\)\.': 'financial closure and support instruments (partially in parallel with formalities).',
    r'CZAS: 1-2 MIESIĄCE': 'TIME: 1-2 MONTHS',
    r'CZAS: OK\. 12 MIESIĘCY': 'TIME: APPROX. 12 MONTHS',
    r'Instalacja przechodzi w tryb stałej monetyzacji\.': 'The installation enters continuous monetization mode.',
    r'Majątek na': 'Wealth for',
    r'Udziały Dziedziczone': 'Inheritable Shares',
    r'Wartość Ziemi Rośnie': 'Land Value Increases',
    r'regulacyjnego to zwykle około 15 years\.': 'regulatory is typically around 15 years.',
    r'To, co dziś bywa kosztem i uciążliwością, wraca na pole jako stabilny nawóz organiczny\.': 'What is today a cost and nuisance, returns to the field as stable organic fertilizer.',
    r'Gnojowica, obornik, odpady kuchenne\. To, co dziś bywa kosztem': 'Slurry, manure, kitchen waste. What is today a cost',
    r'Fermentor pracuje ok\. 39°C\. Higienizacja \(zależnie od wsadu\) redukuje patogeny i nasiona chwastów\.': 'The fermenter operates at approx. 39°C. Hygienization (depending on feedstock) reduces pathogens and weed seeds.',
    r'Poferment wraca na pole jako nawóz organiczny o niższej uciążliwości zapachowej i łatwiejszej aplikacji\.': 'Digestate returns to the field as organic fertilizer with lower odor nuisance and easier application.',
    r'Zamiast płacić za utylizację gnojowicy —': 'Instead of paying for slurry disposal —',
    r'Pilnować\.': 'Supervise.',
    r'Instalacja pracuje automatycznie, a monitoring i reakcję serwisową 24/7 prowadzi zespół Green Plant\.': 'The installation operates automatically, and 24/7 monitoring and service response is handled by the Green Plant team.',
    r'Jakość gazu': 'Gas Quality',
    r'Masz bieżący podgląd produkcji, alarmów i wyniku finansowego\.': 'You have live access to production data, alarms, and financial results.',
    r'System wysyła alert do serwisu Green Plant\. Interwencję organizujemy po': 'The system sends an alert to Green Plant service. We organize an intervention after',
    r'Co miesiąc otrzymujesz raport: energia, ciepło, serwis i wynik': 'Every month you receive a report: energy, heat, service, and results',
    r'Następne <br />': 'Next <br />',
    r'Szybka ocena wsadu, działki i logistyki projektu\.': 'Quick assessment of feedstock, plot, and project logistics.',
    r'Wizyta inżynierska i mapa ryzyk: wsad, przyłącze, formalności\.': 'Engineering visit and risk map: feedstock, grid connection, formalities.',
    r'Podpisujesz LOI, a Green Plant uruchamia formalności i finansowanie\.': 'You sign the LOI, and Green Plant launches formalities and financing.',
    r'Dywidendę z': 'Dividend from',
    r'Obsługę': 'Service',
    r'Masz stały': 'You have a stable',
    r'7–12 tys\. t/rok': '7–12 thousand t/year',
    r'na ~0,7 ha przy źródle wsadu \+ dojazd dla serwisu i dostaw\.': 'on ~0.7 ha near the feedstock source + access for service and deliveries.',
    r'przyłącze i formalności weryfikuje Green Plant \(GPZ/OSD, WZ/pozwolenia, URE\)\.': 'Grid connection and formalities verified by Green Plant (GPZ/OSD, Zoning/permits, URE).',
    r'Jeśli brakuje wsadu w danym roku, SPV może dokupić go z rynku \(mniejszy zysk, ciągłość pracy instalacji\)\.': 'If feedstock is short in a given year, SPV can purchase it from the market (lower profit, but continuous plant operation).',
    r'Materiał informacyjny\. Parametry i podział ekonomiczny zależą od lokalizacji, wsadu, warunków przyłączenia i ustaleń umowy SPV\. Dane liczbowe mają charakter poglądowy i nie stanowią oferty handlowej \(art\. 66 KC\)\.': 'Information material. Parameters and economic division depend on location, feedstock, connection conditions, and SPV agreement. Figures are illustrative and do not constitute a commercial offer.',
    r'kukurydziana\)\. Konserwatywny scenariusz oparty na parametrach możliwych do utrzymania operacyjnie\.': 'corn silage). A conservative scenario based on parameters that are operationally sustainable.',
    r'Przychód z energii': 'Revenue from energy',
    r'PLN / rok \(sprzedaż energii\)': 'PLN / year (energy sales)',
    r'Wkład CAPEX rolnika': 'Farmer\'s CAPEX contribution',
    r'Struktura inwestycji \(przykład\)': 'Investment structure (example)',
    r'Dotacja UE \(KPO / NFOŚiGW\)': 'EU Grant (KPO / NFOŚiGW)',
    r'CAPEX: ~10 mln PLN \| Kredyt obsługiwany przez Green Plant': 'CAPEX: ~10m PLN | Credit serviced by Green Plant',
    r'Dziś: koszt zagospodarowania i transportu': 'Today: management and transport cost',
    r'Po uruchomieniu: wsad pracuje na przychód energii': 'After startup: feedstock works for energy revenue',
    r'Od LOI do pierwszej sprzedaży energii: ok\. 14 miesięcy w jednym, spójnym cyklu inwestycyjnym\.': 'From LOI to the first energy sale: approx. 14 months in one cohesive investment cycle.',
    r'Miesiąc 0 — Start Projektu': 'Month 0 — Project Start',
    r'Miesiące 1-4 — Pozwolenia': 'Months 1-4 — Permits',
    r'Green Plant prowadzi formalności: WZ, warunki przyłączenia i wymagane uzgodnienia\. Ty skupiasz się na gospodarstwie\.': 'Green Plant handles formalities: Zoning, connection conditions, and required agreements. You focus on the farm.',
    r'Miesiące 5-13 — Realizacja': 'Months 5-13 — Execution',
    r'Fundamenty, zbiorniki, CHP, przyłącze i odbiory\.': 'Foundations, tanks, CHP, connection, and acceptance tests.',
    r'Miesiąc 14 — Pierwszy': 'Month 14 — First',
    r'Rozruch i synchronizacja z siecią\. Pierwsze wpływy trafiają na konto SPV\. <strong class="text-gold-accent">Projekt przechodzi w fazę': 'Startup and grid synchronization. Initial revenues hit the SPV account. <strong class="text-gold-accent">Project enters the phase',
    r'SPV porządkuje odpowiedzialność i przepływy\. Land pozostaje po Twojej stronie, a projekt działa w osobnym podmiocie\.': 'The SPV orders responsibilities and cash flows. Land stays on your side, and the project operates in a separate entity.',
    r'Spółka z o\.o\. \(SPV\)': 'Limited Liability Company (SPV)',
    r'Nowy podmiot — oddzielony od Twojego majątku': 'A new entity — separate from your assets',
    r'Wkład Niepieniężny \(Aport\)': 'In-kind Contribution (Aport)',
    r'Land \(0,7 ha\) wnoszony jako aport — nie sprzedaż, nie dzierżawa': 'Land (0.7 ha) contributed as equity — not a sale, not a lease',
    r'Podział Profitów': 'Profit Sharing',
    r'Dividend zgodna z udziałami i umową SPV, bez': 'Dividends in line with shares and SPV agreement, without',
    r'Nie ponosisz odpowiedzialności za awarie': 'You are not liable for breakdowns',
    r'Instalacja może przejść na <span class="text-gold-accent">Ciebie</span>, jeśli tak stanowi umowa\.': 'The plant can pass to <span class="text-gold-accent">You</span>, if the contract so provides.',
    r'praca zależy od serwisu i modernizacji\.': 'operation depends on service and upgrades.',
    r'finansowanie, eksploatację i serwis 24/7 w modelu operatorskim\.': 'financing, operations, and 24/7 service in an operator model.',
    r'dywidendę oraz ciepło użytkowe': 'dividends and usable heat',
    r'Obsługa': 'Handling',
    r'Pełna odpowiedzialność po stronie operatora': 'Full responsibility on the operator side',
    r'Twoja codzienna praca się nie zmienia\. <span class="text-emerald-400">Struktura dochodu już tak\.</span>': 'Your daily work doesn\'t change. <span class="text-emerald-400">Your income structure does.</span>',
    r'PV jest dobrym uzupełnieniem, ale nie homeyka bilansu przez całą dobę\. Poniżej porównanie źródeł z perspektywy gospodarstwa\.': 'PV is a good supplement, but it doesn\'t close the energy balance 24/7. Below is a comparison from the farm\'s perspective.',
    r'Produkcja w nocy / zimą': 'Production at night / in winter',
    r'Częściowo': 'Partially',
    r'Produkcja ciepła': 'Heat production',
    r'Nawóz z procesu': 'Fertilizer from process',
    r'Utylizacja odpadów': 'Waste utilization',
    r'Stability przychodów': 'Revenue Stability',
    r'Zajętość Landu': 'Land Use',
    r'PV jest świetnym uzupełnieniem\. Biogas daje <span class="text-emerald-400">stabilną podstawę 24/7</span>\.': 'PV is an excellent supplement. Biogas provides a <span class="text-emerald-400">stable 24/7 baseload</span>.',
    r'W Bóbrce Ignacy Łukasiewicz uruchamia pionierski szyb naftowy\. Polska buduje przewagę dzięki': 'In Bóbrka, Ignacy Łukasiewicz launches a pioneering oil well. Poland builds its advantage thanks to',
    r'1937 Potęga Gazowa II RP': '1937 Gas Power of the Second Polish Republic',
    r'COP i rozwój przemysłu gazowego pokazały, że energia buduje siłę gospodarki\. Dziś ta sama logika wraca na wieś w zdecentralizowanej formie\.': 'COP and gas industry development proved that energy builds economic power. Today the same logic returns to rural areas in a decentralized form.',
    r'Suwerenność 2\.0': 'Sovereignty 2.0',
    r'Dziś źródłem energii staje się wsad rolniczy\. Biogas łączy Safety energetyczne z': 'Today, agricultural feedstock becomes the energy source. Biogas connects energy security with',
    r'Gnojowica, resztki z pola i odpady rolno-spożywcze stają się paliwem dla instalacji\. Instead of cost': 'Slurry, crop residues, and agri-food waste become fuel for the plant. Instead of cost',
    r'Kluczowy Wskaźnik': 'Key Indicator',
    r'1 tona tłuszczu ≈ 900 m3 biogazu': '1 ton of fat ≈ 900 m3 of biogas',
    r'Wysłodki Buraczane • Wywar •': 'Beet Pulp • Stillage •',
    r'Prędkość Trawienia': 'Digestion Speed',
    r'Gnojowica • Obornik • Słoma •': 'Slurry • Manure • Straw •',
    r'Białka i Tłuszcze': 'Proteins and Fats',
    r'Waste z ubojni • Resztki Spożywcze •': 'Slaughterhouse Waste • Food Leftovers •',
    r'Ile Czego Na <span class="serif-italic text-emerald-700">Pół': 'How Much Of What On The <span class="serif-italic text-emerald-700">Shelf',
    r'Każdy wsad ma inny potencjał metanowy\. Tabela pokazuje orientacyjne': 'Each feedstock has a different methane potential. The table shows indicative',
    r'Żyto — kiszonka z całych roślin': 'Rye — whole crop silage',
    r'Kiszonka słonecznikowa': 'Sunflower silage',
    r'Trawa sudańska, kiszonka': 'Sudangrass, silage',
    r'Kiszonka z liści buraków': 'Beet leaf silage',
    r'Obornik świński': 'Pig manure',
    r'Obornik bydlęcy': 'Cattle manure',
    r'Obornik koński': 'Horse manure',
    r'Gnojowica bydlęca': 'Cattle slurry',
    r'Gnojowica świńska': 'Pig slurry',
    r'Waste mięsne': 'Meat waste',
    r'Waste żywnościowe \(tłuszcze\)': 'Food waste (fats)',
    r'Wysłodki buraczane \(kiszone\)': 'Beet pulp (ensiled)',
    r'Pełne mleko krowie': 'Whole cow milk',
    r'Wytłoki jabłkowe': 'Apple pomace',
    r'Śruta poekstrakcyjna rzepakowa': 'Rapeseed meal',
    r'Zdalny monitoring i obsługa techniczna': 'Remote monitoring and technical support',
    r'Naprawy i części zamienne': 'Repairs and spare parts',
    r'Administracja i zgodność': 'Administration and compliance',
    r'Wartości poglądowe dla instalacji ~500 kW\. OPEX jest rozliczany w SPV, a realne koszty zależą od technologii, wsadu i ustaleń serwisowych\.': 'Illustrative values for ~500 kW installation. OPEX is accounted for in the SPV, real costs depend on technology, feedstock, and service agreements.',
    r'Rozpad złożonych związków na prostsze frakcje\.': 'Breakdown of complex compounds into simpler fractions.',
    r'Bakterie przekształcają biomasę w kwasy organiczne\.': 'Bacteria convert biomass into organic acids.',
    r'Powstaje octan i wodór, czyli paliwo dla metanogenezy\.': 'Acetate and hydrogen are formed, acting as fuel for methanogenesis.',
    r'To etap, w którym wsad realnie zamienia się w strumień przychodów\.': 'This is the stage where the feedstock truly turns into a revenue stream.',
    r'Mniej emisji, mniejsza ekspozycja na przyszłe koszty\.': 'Fewer emissions, lower exposure to future costs.',
    r'Metan jest ~28x silniejszym gazem cieplarnianym niż CO₂\. Regulacje i koszty emisji będą się zaostrzać\. Przetwarzając go w energię, ograniczasz emisję i budujesz zysk\.': 'Methane is ~28x more potent as a greenhouse gas than CO₂. Regulations and emission costs will tighten. By converting it into energy, you reduce emissions and build profit.',
    r'Solidność Przemysłowa': 'Industrial Solidity',
    r'Schemat procesu: od wsadu do energii, ciepła i pofermentu\.': 'Process diagram: from feedstock to energy, heat, and digestate.',
    r'CIEPŁO': 'HEAT',
    r'Heat użytkowe': 'Usable Heat',
    r'Dla instalacji mikro \(< 0,5 MW\) ścieżka administracyjna bywa prostsza niż dla dużych projektów\.': 'For micro-installations (< 0.5 MW), the administrative path is often simpler than for large projects.',
    r'Green Plant prowadzi proces od lokalnych uzgodnień po wymagania środowiskowe\.': 'Green Plant manages the process from local agreements to environmental requirements.',
    r'Model dobrany do średnich i dużych gospodarstw rolnych\.': 'Model tailored for medium and large agricultural farms.',
    r'PONIŻEJ 0,5 MW': 'BELOW 0.5 MW',
    r'\*Zależnie od lokalizacji, wsadu i decyzji organów\.': '*Depending on location, feedstock, and authority decisions.',
    r'Heat: Twoje <span class="serif-italic text-emerald-700">Drugie Źródło': 'Heat: Your <span class="serif-italic text-emerald-700">Second Source',
    r'W kogeneracji ciepło jest drugim strumieniem wartości obok energii elektrycznej\. To realna oszczędność kosztów operacyjnych gospodarstwa\.': 'In cogeneration, heat is the second value stream alongside electricity. It translates to real savings on farm operational costs.',
    r'Suszarnia Zbóż': 'Grain Dryer',
    r'Suszysz kukurydzę, zboże i siano bez dodatkowego paliwa\. Typowa oszczędność sezonowa: ~40 000 PLN\.': 'You dry corn, grain, and hay without additional fuel. Typical seasonal savings: ~40,000 PLN.',
    r'Ciepła woda i stabilne warunki zimą wspierają dobrostan stada i ograniczają ryzyko kosztownych spadków wydajności\.': 'Warm water and stable conditions in winter support herd welfare and reduce the risk of costly productivity drops.',
    r'węgiel mogą spaść wyraźnie, zależnie od odbioru ciepła\.': 'coal can drop significantly, depending on heat reception.',
    r'ciepła rocznie \(instalacja 0,5 MW\)': 'of heat annually (0.5 MW installation)',
    r'koszt paliwa zewnętrznego w modelu bazowym': 'cost of external fuel in the base model',
    r'dostępność — zima i lato': 'availability — winter and summer',
    r'Gnojowica trafia rurami bezpośrednio do zamkniętych zbiorników\. Brak otwartego składowania mocno ogranicza źródło zapachu\.': 'Slurry is piped directly into closed tanks. The lack of open storage severely limits the odor source.',
    r'Hala Podciśnieniowa': 'Negative Pressure Hall',
    r'Przyjęcie substratów stałych odbywa się w hali z wymuszonym podciśnieniem\. Przy otwarciu bramy powietrze jest <strong>zasysane do środka</strong>, a nie wypychane na zewnątrz\.': 'Solid substrates are received in a hall with forced negative pressure. When the gate opens, air is <strong>sucked inside</strong>, not pushed outside.',
    r'Powietrze wylotowe przechodzi przez płuczki wodne i złoża organiczne, gdzie naturalne mikroorganizmy neutralizują nawet do ~99% związków': 'Exhaust air passes through water scrubbers and organic beds, where natural microorganisms neutralize up to ~99% of compounds',
    r'Społeczna\.': 'Social.',
    r'Dobrze zaprojektowana instalacja ogranicza uciążliwości dla otoczenia i zwiększa Safety społeczne projektu\.': 'A well-designed plant reduces nuisance for the surroundings and increases the social safety of the project.',
    r'Sąsiedzi i ': 'Neighbors and ',
    r'Dobrze poprowadzony projekt daje gminie energię, ciepło i podatki lokalne zamiast napięć społecznych\.': 'A well-run project provides the municipality with energy, heat, and local taxes instead of social tensions.',
    r'Tanie ciepło dla obiektów użyteczności publicznej': 'Cheap heat for public utility buildings',
    r'Dla Sąsiadów': 'For Neighbors',
    r'Niższa uciążliwość zapachowa niż przy otwartym magazynowaniu': 'Lower odor nuisance than with open storage',
    r'Możliwość przyjmowania ciepła po niższej cenie': 'Opportunity to receive heat at a lower price',
    r'Wspólne korzyści z Klastra Energii': 'Shared benefits from the Energy Cluster',
    r'Gotowe Narzędzia': 'Ready Tools',
    r'Wzór pisma do Sołtysa': 'Letter template for the Village Head',
    r'Konsultacje społeczne \(Green Plant prowadzi\)': 'Public consultations (managed by Green Plant)',
    r'Nie budujemy obok społeczności\. Budujemy wartość <strong>razem</strong> z nią\.': 'We don\'t build next to the community. We build value <strong>together</strong> with them.',
    r'Lat Doświadczenia': 'Years of Experience',
    r'Zespół kierowniczy z doświadczeniem w sektorze OZE, energetyce i': 'Management team with experience in the RES, energy sector, and',
    r'Finansowanie Własne': 'In-house Financing',
    r'Green Plant wnosi kapitał i finansowanie projektu\. Nie oczekujemy od rolnika wkładu inwestycyjnego\.': 'Green Plant provides capital and project financing. We do not expect an investment contribution from the farmer.',
    r'Pełna Obsługa': 'Full Service',
    r'Pozwolenia, realizacja, przyłącze OSD, serwis, rozliczenia, ubezpieczenie — jeden partner na całość\.': 'Permits, execution, DSO grid connection, service, billing, insurance — one partner for everything.',
    r'Potencjał biometanu pozostaje wielokrotnie większy niż obecna skala': 'Biomethane potential remains many times greater than the current scale',
    r'Istniejących Jednostek': 'Existing Units',
    r'Potencjał Gmin': 'Municipal Potential',
    r'Wykorzystany Potencjał': 'Utilized Potential',
    r'Polska może stać się biometanowym spichlerzem Europy': 'Poland can become the biomethane granary of Europe',
    r'Wartości orientacyjne, oparte na szacunkach branżowych\.': 'Indicative values, based on industry estimates.',
    r'Przyłączeniowa': 'Connection',
    r'Connection capacity jest kluczowym ograniczeniem projektu\. Green Plant prowadzi analizę i proces przyłączeniowy': 'Connection capacity is a key project constraint. Green Plant conducts the analysis and connection process',
    r'Mniej Zakupów Nawozów <span class="serif-italic text-emerald-700">Mineralnych\.</span>': 'Fewer Mineral Fertilizer Purchases <span class="serif-italic text-emerald-700">Mineral.</span>',
    r'Poferment stabilizuje koszty nawożenia i poprawia': 'Digestate stabilizes fertilization costs and improves',
    r'Oszczędność NPK': 'NPK Savings',
    r'przyswajalny przez rośliny\.': 'assimilable by plants.',
    r'<strong>Możesz istotnie ograniczyć zakup nawozów mineralnych\.</strong>': '<strong>You can significantly reduce the purchase of mineral fertilizers.</strong>',
    r'Budowa Próchnicy': 'Humus Building',
    r'Trudno rozkładalny węgiel \(lignina\) przetrwa proces\. Przy rozsiewaniu wspiera budowę materii organicznej i poprawę struktury gleby\.': 'Hard-to-decompose carbon (lignin) survives the process. During spreading, it supports organic matter building and soil structure improvement.',
    r'jako wartość gospodarstwa': 'as farm value',
    r'Poferment: Twój <span class="serif-italic text-emerald-700">Nawóz': 'Digestate: Your <span class="serif-italic text-emerald-700">Fertilizer',
    r'Fermentacja zmienia formę składników odżywczych tak, by szybciej pracowały w polu i były prostsze w aplikacji\.': 'Fermentation changes the form of nutrients so they work faster in the field and are easier to apply.',
    r'Forma amonowa — szybciej dostępna dla roślin': 'Ammonium form — faster availability to plants',
    r'Oszczędność: ~800 PLN/ha/rok': 'Savings: ~800 PLN/ha/year',
    r'Mineralizowany — wysoka biodostępność': 'Mineralized — high bioavailability',
    r'Oszczędność: ~400 PLN/ha/rok': 'Savings: ~400 PLN/ha/year',
    r'W dużej mierze zachowany — niskie straty': 'Largely preserved — low losses',
    r'Oszczędność: ~300 PLN/ha/rok': 'Savings: ~300 PLN/ha/year',
    r'<strong>Mniejszy odór</strong> — fermentacja rozbija lotne kwasy': '<strong>Lower odor</strong> — fermentation breaks down volatile acids',
    r'<strong>Redukcja patogenów</strong> — higienizacja \(zależnie od wsadu\)': '<strong>Pathogen reduction</strong> — hygienization (depending on feedstock)',
    r'<strong>Lepsza penetracja</strong> — niższa lepkość, równomierny rozsiew': '<strong>Better penetration</strong> — lower viscosity, even spreading',
    r'<strong>Mniej chwastów</strong> — nasiona niszczone w procesie': '<strong>Fewer weeds</strong> — seeds destroyed in the process',
    r'Łączna oszczędność na nawozach': 'Total savings on fertilizers',
    r'PROMIEŃ:': 'RADIUS:',
    r'Instalacja stoi przy źródle wsadu\. Minimalizujesz logistykę i koszty transportu\.': 'The plant stands at the feedstock source. You minimize logistics and transport costs.',
    r'Najtańszy kilometr transportu to ten, którego nie musisz wykonać\.': 'The cheapest transport kilometer is the one you don\'t have to make.',
    r'Jak <span class="serif-italic text-emerald-700">Wygląda Współpraca\.</span>': 'How <span class="serif-italic text-emerald-700">Cooperation Looks.</span>',
    r'Pełna ścieżka: od pierwszej rozmowy do pierwszego miesiąca': 'The full path: from the first conversation to the first month',
    r'Krótka rozmowa i wstępny screening lokalizacji pod wsad, działkę i przyłącze\.': 'Brief talk and initial site screening for feedstock, plot, and connection.',
    r'Wizyta inżynierów\. Sprawdzenie Landu, przyłącza GPZ,': 'Engineers\' visit. Land check, GPZ connection,',
    r'Prowadzimy decyzje środowiskowe, budowlane i przyłączeniowe\. Ty akceptujesz dokumenty i podpisujesz umowę SPV\.': 'We manage environmental, building, and connection decisions. You accept the documents and sign the SPV agreement.',
    r'Od tego momentu projekt pracuje na miesięczny przychód SPV\. Horyzont wsparcia: zwykle do 15 years \(zależnie od systemu\)\.': 'From this point, the project works on monthly SPV revenue. Support horizon: typically up to 15 years (depending on the system).',
    r'CZĘŚĆ II': 'PART II',
    r'Od lokalnej suwerenności do bezpiecznej przyszłości\.': 'From local sovereignty to a secure future.',
    r'Suwerenność <br />': 'Sovereignty <br />',
    r'Najbardziej odporna energia to ta, którą produkujesz lokalnie\.': 'The most resilient energy is the one you produce locally.',
    r'Polska wieś przestaje być biorcą energii, a staje się jej <strong>dostawcą</strong>\. Biogas plant stabilizuje lokalny bilans prądu i ciepła\.': 'The Polish countryside ceases to be an energy recipient and becomes its <strong>supplier</strong>. A biogas plant stabilizes the local electricity and heat balance.',
    r'Pieniądz w': 'Money in',
    r'Większa część wartości zostaje w regionie: u rolników, wykonawców i lokalnych usługodawców\.': 'The bulk of value remains in the region: with farmers, contractors, and local service providers.',
    r'Mechanizm FIT/FIP stabilizuje cenę energii nawet do 15 years, a OSD realizuje obowiązek zakupu zgodnie z warunkami wsparcia\.': 'The FIT/FIP mechanism stabilizes energy prices for up to 15 years, and the DSO fulfills the purchase obligation as per support conditions.',
    r'Rosnące cele NCW zwiększają zapotrzebowanie sektora paliwowego na': 'Growing NCR targets increase the fuel sector\'s demand for',
    r'Programy KOWR i ARiMR wspierają inwestycje rolnicze w biogaz oraz infrastrukturę towarzyszącą\.': 'KOWR and ARiMR programs support agricultural investments in biogas and associated infrastructure.',
    r'Dopłaty <span class="serif-italic text-emerald-700">Bezpieczne\.</span>': 'Subsidies <span class="serif-italic text-emerald-700">Secured.</span>',
    r'Projekt jest prowadzony tak, by chronić bieżące dopłaty i jednocześnie otwierać dodatkowe źródła finansowania\.': 'The project is managed to protect current subsidies while unlocking additional funding sources.',
    r'Dopłaty Zachowane': 'Subsidies Retained',
    r'Płatności bezpośrednie \(WPR/CAP\) — bez zmian': 'Direct payments (CAP) — unchanged',
    r'Klasyfikacja Landów — zmiana tylko 0,7 ha': 'Land Classification — change only on 0.7 ha',
    r'rolnika — niezagrożony': 'farmer — not threatened',
    r'Nowe Źródła Finansowania': 'New Funding Sources',
    r'NFOŚiGW —': 'NFOŚiGW —',
    r'Certyfikaty / Świadectwa Pochodzenia': 'Certificates / Guarantees of Origin',
    r'Green Plant zajmuje się wszystkimi wnioskami o dofinansowanie\.': 'Green Plant handles all grant applications.',
    r'Odpadów': 'Waste',
    r'Strumień Wartości\.': 'Value Stream.',
    r'Podczas uszlachetniania biogazu wychwytujemy <strong>biogeniczne CO₂</strong>\. To strumień, który można dodatkowo monetyzować w wybranych zastosowaniach przemysłowych\.': 'During biogas upgrading, we capture <strong>biogenic CO₂</strong>. This is a stream that can be additionally monetized in select industrial applications.',
    r'Bąbelki Klasy Spożywczej': 'Food Grade Bubbles',
    r'Suchy Lód': 'Dry Ice',
    r'Łańcuch Chłodniczy': 'Cold Chain',
    r'Skąd Płyną <span class="serif-italic text-gold-accent">Pieniądze\.</span>': 'Where Does The <span class="serif-italic text-gold-accent">Money Flow From.</span>',
    r'Rozkład ekonomiki SPV w scenariuszu bazowym \(energia: 800 PLN/MWh\)\.': 'SPV economic breakdown in the baseline scenario (energy: 800 PLN/MWh).',
    r'PLN / rok \(marża 56%\)': 'PLN / year (margin 56%)',
    r'Instalacja pracuje równolegle do gospodarstwa i stabilizuje rytm pracy przez cały rok\.': 'The plant operates parallel to the farm and stabilizes the workflow year-round.',
    r'oborę i home<br>• drying drewna opałowego<br>• Poferment magazynowany': 'barn and home<br>• firewood drying<br>• Digestate stored',
    r'nawozów mineralnych<br>• Kiszonka z poplonów → fermentor<br>• Electricity sprzedawany do sieci': 'mineral fertilizers<br>• Catch crop silage → fermenter<br>• Electricity sold to the grid',
    r'Suszarnia zbóż na ciepło własne<br>• Trawy pokosne → substrat<br>• Szczytowa produkcja prądu<br>• Heat → drying siana': 'Grain dryer on own heat<br>• Mowed grass → substrate<br>• Peak electricity production<br>• Heat → hay drying',
    r'Jesień': 'Autumn',
    r'Kiszonka z kukurydzy → zbiornik<br>• Wysłodki buraczane → fermentor<br>• Przygotowanie na zimę<br>• Roczne rozliczenie FIT': 'Corn silage → tank<br>• Beet pulp → fermenter<br>• Winter prep<br>• Annual FIT settlement',
    r'Biogas plant nie zakłóca kalendarza rolnika —': 'The biogas plant doesn\'t disrupt the farmer\'s calendar —',
    r'A Co Jeśli <span': 'And What If <span',
    r'Brak decyzji także kosztuje\. Poniżej porównanie ciężaru pozostania przy obecnym modelu vs\. wejście w biogaz\.': 'Indecision also has a cost. Below is a comparison of the burden of staying with the current model vs. entering biogas.',
    r'Rosnące Koszty': 'Rising Costs',
    r'Nawozy mineralne: duża zmienność cen': 'Mineral fertilizers: high price volatility',
    r'Koszty produkcji rolnej rosną i potrafią zmieniać się': 'Agricultural production costs are rising and can fluctuate',
    r'Energia elektryczna: rosnące koszty': 'Electricity: rising costs',
    r'Ceny energii i opłat sieciowych pozostają istotnym': 'Energy and grid fees remain a significant',
    r'Utylizacja odpadów — nowe obowiązki': 'Waste disposal — new obligations',
    r'Wymogi, kontrole i koszty wokół odpadów będą rosnąć': 'Requirements, inspections, and costs around waste will rise',
    r'Z Biogasownią': 'With a Biogas Plant',
    r'Własny nawóz organiczny \(poferment\)': 'Own organic fertilizer (digestate)',
    r'Ograniczasz ekspozycję na zmienność cen nawozów': 'You limit exposure to fertilizer price volatility',
    r'Własna energia 24/7': 'Own energy 24/7',
    r'Produkcja prądu i ciepła na miejscu — rachunki mogą spaść znacząco': 'On-site power and heat production — bills can drop significantly',
    r'Waste stają się wsadem': 'Waste becomes feedstock',
    r'Gnojowica przestaje być kosztem i pracuje jako wsad': 'Slurry ceases to be a cost and works as feedstock',
    r'Każdy rok <span class="text-red-400">bez</span> biogazowni to <span': 'Every year <span class="text-red-400">without</span> a biogas plant is <span',
    r'Największą przewagę budują gospodarstwa, które wchodzą wcześniej, homeykają przyłącza i zabezpieczają optymalne lokalizacje\.': 'The biggest advantage is built by farms that enter early, secure connections, and lock in optimal locations.',
    r'pojawia się skala ~1 500 instalacji do 2030 roku\.': 'a scale of ~1,500 plants by 2030 emerges.',
    r'Dochód Miesięczny': 'Monthly Income',
    r'stabilny filar energetyczny przez cały rok\.': 'a stable energy pillar year-round.',
    r'Ryzyko Konfliktów': 'Risk of Conflicts',
    r'Hermetyczny proces i biofiltry ograniczają uciążliwości zapachowe\.': 'Hermetic process and biofilters limit odor nuisance.',
    r'gospodarstwa niezależnie od koniunktury rynkowej czy pogody\."': 'of the farm regardless of market conditions or weather."',
    r'opracowania branżowe, 2025': 'industry reports, 2025',
    r'Jesteś <span class="serif-italic text-gold-accent">Współwłaścicielem\.</span> Na lata\.': 'You are a <span class="serif-italic text-gold-accent">Co-owner.</span> For years.',
    r'Nie jesteś dzierżawcą ani klientem\. Jesteś udziałowcem SPV, a wypracowana wartość zostaje w gospodarstwie\.': 'You are not a lessee or a client. You are an SPV shareholder, and the generated value stays on the farm.',
    r'SPV produkuje prąd, ciepło i poferment\. Projekt pracuje od rozruchu, a udziały pozostają po Twojej stronie\.': 'SPV produces electricity, heat, and digestate. The project operates from startup, and the shares remain on your side.',
    r'Faza 2: Portfolio Projektów': 'Phase 2: Project Portfolio',
    r'Green Plant buduje sieć 200 biogazowni z rolnikami w całej Polsce\.': 'Green Plant is building a network of 200 biogas plants with farmers across Poland.',
    r'Rozwój skali może wzmacniać pozycję rynkową projektu, a Twoje udziały w SPV': 'Scaling up can strengthen the project\'s market position, and your SPV shares',
    r'mogą rosnąć na wartości\.': 'can grow in value.',
    r'Współwłaściciel': 'Co-owner',
    r'nie dzierżawca, nie klient': 'not a lessee, not a client',
    r'Wzrost wartości': 'Value Growth',
    r'Udziały nie mają z góry narzuconej daty wygaśnięcia': 'Shares do not have a predetermined expiration date',
    r'Pytania <span class="serif-italic text-emerald-700">Rolników</span>': 'Questions from <span class="serif-italic text-emerald-700">Farmers</span>',
    r'Najczęstsze pytania, które słyszymy podczas wizyt w gospodarstwach i spotkań lokalnych\.': 'The most common questions we hear during farm visits and local meetings.',
    r'"Ile ziemi stracę\?"': '"How much land will I lose?"',
    r'Instalacja zajmuje ~0,7 ha \(ok\. 0,4% przy 180 ha\)\. Reszta pól pracuje normalnie — a nawet lepiej dzięki pofermentowi\.': 'The plant takes up ~0.7 ha (approx. 0.4% on 180 ha). The rest of the fields work normally — and even better thanks to the digestate.',
    r'"Czy muszę mieć 200 krów\?"': '"Do I need to have 200 cows?"',
    r'Nie\. Liczy się bilans wsadu i logistyka\. Można pracować na miksie z kilku': 'No. Feedstock balance and logistics are what counts. We can work on a mix from several',
    r'"Co jeśli Green Plant zbankrutuje\?"': '"What if Green Plant goes bankrupt?"',
    r'zostają u Ciebie\. Udziały są zbywalne\.': 'stay with you. Shares are transferable.',
    r'"A moje dopłaty bezpośrednie\?"': '"What about my direct payments?"',
    r'Bez zmian\. Płatności WPR naliczane są na uprawy\. Biogas plant': 'No changes. CAP payments are calculated per crop. The biogas plant',
    r'Zwykle około 1 godziny na logistykę wsadu\. Monitoring, serwis i': 'Usually about 1 hour for feedstock logistics. Monitoring, service, and',
    r'"Czy mogę wyjść z umowy\?"': '"Can I exit the contract?"',
    r'Tak\. Umowa SPV przewiduje klauzule zbycia udziałów — możesz je sprzedać or przekazać dzieciom jako gotowy majątek\.': 'Yes. The SPV agreement includes share transfer clauses — you can sell them or hand them over to your children as ready wealth.',
    r'Ten sam wsad może pracować w dwóch modelach: sprzedaż surowca albo udział w marży energetycznej\. Porównanie dla 9 000 ton rocznie\.': 'The same feedstock can work in two models: raw material sale or a share in the energy margin. Comparison for 9,000 tons annually.',
    r'Tradycyjna Sprzedaż': 'Traditional Sale',
    r'Przychód ze sprzedaży \(180 zł/t\)': 'Revenue from sale (180 PLN/t)',
    r'Koszt produkcji \(140 zł/t\)': 'Production cost (140 PLN/t)',
    r'Risk: zmienność cen skupu, koszt nawożenia i brak wpływu na marżę końcową\.': 'Risk: purchase price volatility, fertilization costs, and no influence on the final margin.',
    r'Prognozowany udział \(60%\)': 'Forecasted share (60%)',
    r'Oszczędność na nawozach \(NPK\)': 'Savings on fertilizers (NPK)',
    r'Realna korzyść roczna': 'Real annual benefit',
    r'większy zysk z hektara niż przy sprzedaży\.': 'higher profit per hectare than with selling.',
    r'Dodatkowo: miks z własną gnojowicą może ograniczać koszt dokupowanego wsadu\.': 'Additionally: mixing with your own slurry can reduce the cost of purchased feedstock.',
}

for file in files:
    with open(file, "r", encoding="utf-8") as f:
        content = f.read()

    for k, v in replacements.items():
        content = re.sub(k, v, content, flags=re.IGNORECASE)

    with open(file, "w", encoding="utf-8") as f:
        f.write(content)

print("Remaining Polish replacements complete.")
